-- https://github.com/petersm3/roae
-- Developed with AI assistance (Claude, Anthropic)
/-
  PruneGInvariance.lean — machine-checked G-invariance of the v4 prune stack
  #67/#68/#70 (2026-07-14, v4-canonical branch; test-plan tier T3.6).
  Core Lean 4 only (no mathlib). Standalone: `lean PruneGInvariance.lean`.

  Companion to PruneExactness.lean: that file machine-checks that the three
  prune predicates are SOUND (a fired prune removes only provably-dead
  subtrees). This file machine-checks that they are G-INVARIANT — each
  predicate takes the same value on a search state and on its image under
  any relabeling σ in the 48-element symmetry group G48 (the centralizer of
  bit-reversal, Automorphism.lean / SYMMETRY_SEARCH.md). G-invariance is the
  missing formal leg of the orbit work-invariance argument behind the ×36
  orbit-reduction economics (symmetry review Q1/Q3; red-team review §2b):
  per-cell DFS work = min(tree, B), and if the walked tree is orbit-invariant
  then walking one representative per orbit costs exactly 1/|orbit| of the
  full walk. The tree is generated by (expand, prune); Automorphism.lean's
  constraint invariance covers the constraint side, and this file covers the
  prune side, with the expansion side left as the stated bridge below (its
  empirical witness is test-plan T1.6: node-count equality across a full
  orbit with the final predicate set — "verified, not assumed").

  The three predicates (see solve.c, search "task #67", "task #68",
  "task #70"), modeled here on the placed prefix `seq : List Nat` (hexagram
  values in placement order; position of v = its index in seq):

  · #67 mid-walk C3: fires when the partial complement-distance
    Σ_{h<64, h and h⊕63 both placed} |pos(h) − pos(h⊕63)|  (= solve.c's
    mw_partial_cd_x64; summing over all 64 h counts each unordered
    complement pair twice, which is exactly compute_comp_dist_x64's ×2
    convention) already exceeds the threshold (kw_comp_dist_x64 = 776).
  · #70 optimistic completion bound: adds the inevitable future
    contribution 2 × (#complement pairs not yet both-placed)
    (= Σ_{h<64} [¬ both-placed h], same double-counting absorbs the ×2);
    fires when partial + bound > threshold.
  · #68 C5 feasibility: fires when for some distance class d the remaining
    C5 budget budget[d] is smaller than the number of unplaced C1 partner
    pairs whose within-pair distance is d. Modeled with both sides doubled
    (counting hexagrams h < 64 instead of unordered pairs counts each
    unplaced pair twice, and budget[d] < n ⟺ 2·budget[d] < 2n), and with
    budget[d] = target(d) − (count of class-d transitions consumed by the
    prefix), which is how solve.c maintains budget[] (one decrement per
    consumed transition).

  What is machine-checked here (model level):
  · `partialCd_mapP`, `inevitableBound_mapP`, `budgetOf_mapP`,
    `unusedWd2_mapP` — every quantity the predicates read is G-invariant:
    relabeling by σ ∈ G48 preserves positions (values move, slots do not),
    commutes with complement (applyPerm_comp63) and with the C1 partner map
    (applyPerm_partner), preserves Hamming distances (applyPerm_isometry),
    and permutes the index set h < 64, so each sum/count merely reindexes.
  · `prune67_mapP`, `prune70_mapP`, `prune68_mapP`, `pruneV4_mapP` —
    the prune predicates therefore satisfy prune(σ·s) = prune(s), for any
    threshold and any budget target.
  · `runningG_mapP` / `runningG_orbit_invariant` (§9, added 2026-07-22) —
    the C3 G-channel DP's prefix running-G (open at slot s: g −= s; close:
    g += s; self-pair: unchanged) is G-invariant on placement prefixes —
    the quotient-compatibility lemma promised (as prose) by the G-channel
    design §1.2/§2.5 (roae-private DESIGN_C3_GCHANNEL_2026_07_21.md):
    running-G rides the canonical-mask quotient exactly like rid.
  · `treeCount_equivariant`, `work_orbit_invariant`,
    `pruneV4_work_invariant` — the packaging: for a tree generated by
    children(s) = if prune s then [] else expand s, if prune is invariant
    and expansion commutes with the relabeling UP TO PERMUTATION of the
    children list, then node counts — hence per-cell work min(tree, B), for
    every budget B — are equal at σ-corresponding roots. Order of children
    is deliberately not required (solve.c's rarity-sorted pair_order breaks
    ties by pair index, which is not σ-invariant; node COUNT and therefore
    work min(tree,B) do not depend on it, though which records are found
    at a non-exhaustive budget does — that is the budget-frontier issue of
    the red-team review §1.3, out of scope here).

  Bridge facts (stated, NOT machine-checked — the PartitionInvariance.lean
  pattern; covered by the runtime gates, code review, and test T1.6):
  · solve.c's mw_pos[]/mw_partial_cd_x64 equal the model's positions and
    partialCd; mw_inevitable_remaining_cd_x64 equals inevitableBound;
    kw_comp_dist_x64 = 776.
  · solve.c's budget[] equals budgetOf with target = the exact C5
    distribution {1:2, 2:20, 3:13, 4:19, 6:9} (budget stays nonnegative on
    walked states, so ℕ truncated subtraction agrees), and
    unused_wd_count[d] = unusedWd2/2 (the doubled comparison in prune68 is
    equivalent to the C comparison).
  · the candidate-generation step of the DFS commutes with relabeling up to
    permutation of the children list (`he` hypothesis of
    pruneV4_work_invariant) — empirical witness: T1.6 node-count equality
    across one full orbit; and `fuel` ≥ the walk depth (≤ 32).

  Attribution / novelty note: orbit invariance of isomorph-closed search is
  classical (Burnside-style orbit counting; standard in isomorph-free
  exhaustive generation, e.g. McKay); nothing here is claimed as novel —
  only this machine-checked packaging for these three predicates is ours
  (to our knowledge; corrections welcome). Paper argument:
  V4_REVIEW_A_SYMMETRY_2026_07_13 Q1/Q3 and V4_REVIEW_REDTEAM_2026_07_13 §2b
  (roae-private); empirical witness: V4_VALIDATION_TEST_PLAN T1.6.

  The defs pc6/rev6/partner/ham/transitions/inserts/perms/applyPerm/idp/G48
  are restated verbatim from KingWen.lean / Automorphism.lean (the files are
  standalone; no lake project), as are the finite facts and the list
  utilities reused.

  Trust base (updated 2026-08-04, per the standing native_decide → decide
  migration policy in lean/README.md): kernel-only end to end — ZERO
  native_decide anywhere in this file. The §1 group facts applyPerm_lt64 /
  applyPerm_comp63 / applyPerm_partner / applyPerm_range_perm are kernel
  `decide`; applyPerm_inj is derived structurally from applyPerm_range_perm;
  and applyPerm_isometry — this file's last native_decide until 2026-08-04
  (the 2026-07-22 note here recorded kernel-`decide` exhaustion on the
  48 × 64 × 64 ENUMERATION; true of that route, moot for this one) — is now
  an instantiation of §0b's structural general isometry
  (applyPerm_isometry_perm: ANY bit-position permutation preserves ham on
  ALL naturals — classical coding theory, credited as such, no novelty
  claimed). So the #67/#70 chain, the #68 leg (wdTerm/transitions/budget),
  pruneV4_mapP, and the §9 prefix-G chain all rest on the kernel alone.
  The §8 sanity instantiations are `decide +kernel` (kernel-evaluated, no
  compiler trust) since 2026-08-04.

  §9 attribution: identified as the one promised-but-unlanded piece by the
  C3 adversarial review (roae-private REVIEW_C3_FABLE_2026_07_22.md §1.4/§3);
  formalization by Claude (Fable 5), 2026-07-22. No novelty claimed —
  invariance of a slot-weighted statistic under a value-relabeling group is
  elementary; this is only its machine-checked packaging for this DP
  (corrections welcome).
-/

namespace PruneGInvariance

/- ------------- §0 defs restated verbatim from KingWen.lean / Automorphism.lean ------------- -/

/-- popcount for 6-bit values (total, no recursion needed). -/
def pc6 (n : Nat) : Nat :=
  n % 2 + n / 2 % 2 + n / 4 % 2 + n / 8 % 2 + n / 16 % 2 + n / 32 % 2

/-- 6-bit reversal. -/
def rev6 (n : Nat) : Nat :=
  n % 2 * 32 + n / 2 % 2 * 16 + n / 4 % 2 * 8 + n / 8 % 2 * 4 + n / 16 % 2 * 2 + n / 32 % 2

/-- canonical partner: reversal, or complement for palindromes. -/
def partner (h : Nat) : Nat := if rev6 h = h then h ^^^ 63 else rev6 h

/-- Hamming distance on 6-bit values. -/
def ham (a b : Nat) : Nat := pc6 (a ^^^ b)

/-- adjacent-transition distances of a sequence. -/
def transitions (l : List Nat) : List Nat :=
  (l.zip l.tail).map (fun p => ham p.1 p.2)

/-- all permutations of a list (insertion-based; 720 elements for 6 positions). -/
def inserts (x : Nat) : List Nat → List (List Nat)
  | [] => [[x]]
  | y :: ys => (x :: y :: ys) :: (inserts x ys).map (y :: ·)

def perms : List Nat → List (List Nat)
  | [] => [[]]
  | x :: xs => (perms xs).flatMap (inserts x)

/-- apply a bit-position permutation p (bit i of n goes to position p[i]). -/
def applyPerm (p : List Nat) (n : Nat) : Nat :=
  ((List.range 6).map fun i => n / (2^i) % 2 * 2^(p.getD i 0)).foldl (·+·) 0

/-- the identity bit permutation. -/
def idp : List Nat := [0, 1, 2, 3, 4, 5]

/-- G48 = the centralizer of bit-reversal among the 720 bit permutations
    (order 48, ≅ B₃ ≅ Z₂ ≀ S₃ — the symmetry group of SYMMETRY_SEARCH.md). -/
def G48 : List (List Nat) :=
  (perms idp).filter fun p =>
    (List.range 64).all fun h => applyPerm p (rev6 h) == rev6 (applyPerm p h)


/- ------------- §0b the structural Hamming-isometry layer (added 2026-08-04) -------------
   Proves the CLASSICAL coding-theory fact that permuting coordinates is an
   isometry of the Hamming metric (the reason permutation-equivalent codes
   share a weight distribution) — structurally, with no case enumeration:
   ham a b is the size of the disagreement set {i < 6 : bit i a ≠ bit i b};
   applyPerm p relocates bit i to position p[i] (`bitsum_bit_getD`), so p
   carries the disagreement set of (a,b) bijectively onto that of (p·a, p·b),
   and the disagreement sum merely reindexes along p (`sum_perm`). Nothing
   here is novel; it replaces the former native_decide enumeration of §1's
   applyPerm_isometry. Tiny-domain kernel `decide`s used (disclosed): the
   6-element literal idp.Nodup and 0 < 2 — nothing over perms/G48/hexagrams. -/

/-- sum preserved under list permutation (moved here from §2, 2026-08-04 —
    the isometry layer needs it before §1). -/
theorem sum_perm {l₁ l₂ : List Nat} (h : l₁.Perm l₂) : l₁.sum = l₂.sum := by
  induction h with
  | nil => rfl
  | cons x _ ih => simp [ih]
  | swap x y l => simp [List.sum_cons]; omega
  | trans _ _ ih₁ ih₂ => omega

/-- membership in `inserts x l` means: a permutation of x :: l (structural). -/
theorem mem_inserts_perm {x : Nat} : ∀ {l q : List Nat}, q ∈ inserts x l → q.Perm (x :: l)
  | [], q, hq => by
      simp only [inserts, List.mem_cons, List.not_mem_nil, or_false] at hq
      subst hq; exact List.Perm.refl _
  | y :: ys, q, hq => by
      simp only [inserts, List.mem_cons, List.mem_map] at hq
      rcases hq with rfl | ⟨q', hq', rfl⟩
      · exact List.Perm.refl _
      · exact (List.Perm.cons y (mem_inserts_perm hq')).trans (List.Perm.swap x y ys)

/-- every member of `perms l` is a permutation of l (structural induction on
    the generators; the converse is not needed). -/
theorem mem_perms_perm : ∀ {l q : List Nat}, q ∈ perms l → q.Perm l
  | [], q, hq => by
      simp only [perms, List.mem_cons, List.not_mem_nil, or_false] at hq
      subst hq; exact List.Perm.refl _
  | x :: xs, q, hq => by
      simp only [perms, List.mem_flatMap] at hq
      obtain ⟨r, hr, hq2⟩ := hq
      exact (mem_inserts_perm hq2).trans (List.Perm.cons x (mem_perms_perm hr))

theorem foldl_add_eq_sum : ∀ (l : List Nat) (a : Nat), l.foldl (·+·) a = a + l.sum
  | [], a => by simp
  | x :: xs, a => by
      rw [List.foldl_cons, foldl_add_eq_sum xs (a + x), List.sum_cons]
      omega

theorem getD_mem : ∀ (l : List Nat) (k : Nat), k < l.length → l.getD k 0 ∈ l
  | [], _, h => by simp at h
  | x :: xs, 0, _ => by simp
  | x :: xs, k+1, h => by
      rw [List.getD_cons_succ]
      exact List.mem_cons_of_mem x (getD_mem xs k (by simpa using h))

/-- reindexing a map through positional lookup. -/
theorem map_getD_comp (l : List Nat) (f : Nat → Nat) :
    l.map f = (List.range l.length).map (fun i => f (l.getD i 0)) := by
  induction l with
  | nil => rfl
  | cons x xs _ =>
      rw [List.length_cons, List.range_succ_eq_map, List.map_cons, List.map_cons,
        List.map_map]
      congr 1

/-- the bit-scatter normal form: bitsum q n = Σ_i bit_i(n) · 2^(q_i). -/
def bitsum : List Nat → Nat → Nat
  | [], _ => 0
  | x :: xs, n => n % 2 * 2^x + bitsum xs (n / 2)

theorem range_map_bits (q : List Nat) : ∀ n : Nat,
    ((List.range q.length).map fun i => n / 2^i % 2 * 2^(q.getD i 0)).sum = bitsum q n := by
  induction q with
  | nil => intro n; rfl
  | cons x xs ih =>
      intro n
      rw [List.length_cons, List.range_succ_eq_map, List.map_cons, List.map_map, List.sum_cons]
      have hhead : n / 2^0 % 2 * 2^((x :: xs).getD 0 0) = n % 2 * 2^x := by
        simp
      have htail : ((List.range xs.length).map
          ((fun i => n / 2^i % 2 * 2^((x :: xs).getD i 0)) ∘ Nat.succ)).sum
          = bitsum xs (n / 2) := by
        rw [← ih (n / 2)]
        apply congrArg
        apply List.map_congr_left
        intro i _
        simp only [Function.comp, Nat.succ_eq_add_one, List.getD_cons_succ]
        have hdiv : n / 2 ^ (i + 1) = n / 2 / 2 ^ i := by
          rw [Nat.div_div_eq_div_mul, ← Nat.pow_succ']
        rw [hdiv]
      rw [hhead, htail]
      rfl

theorem applyPerm_eq_bitsum (p : List Nat) (hlen : p.length = 6) (n : Nat) :
    applyPerm p n = bitsum p n := by
  unfold applyPerm
  rw [foldl_add_eq_sum, Nat.zero_add, ← hlen, range_map_bits]

/-- the arithmetic workhorse: adding c·2^x (c < 2) to a number whose bit x is
    clear changes bit x to c and no other bit — no carries. Purely arithmetic
    (division/modulus); here for the j > x side. -/
theorem bit_add_high {c T x j : Nat} (hc : c < 2) (hT : T / 2^x % 2 = 0) (hj : x < j) :
    (c * 2^x + T) / 2^j % 2 = T / 2^j % 2 := by
  have hqe : T / 2^x = 2 * (T / 2^(x+1)) := by
    have h1 := Nat.div_add_mod (T / 2^x) 2
    have h2 : T / 2^x / 2 = T / 2^(x+1) := by
      rw [Nat.div_div_eq_div_mul, ← Nat.pow_succ]
    rw [h2] at h1
    omega
  have hmul : 2^x * (2 * (T / 2^(x+1))) = 2^(x+1) * (T / 2^(x+1)) := by
    rw [Nat.pow_succ, Nat.mul_assoc]
  have hTdecomp : T = 2^(x+1) * (T / 2^(x+1)) + T % 2^x := by
    have h3 := Nat.div_add_mod T (2^x)
    rw [hqe, hmul] at h3
    exact h3.symm
  have hr : T % 2^x < 2^x := Nat.mod_lt _ (Nat.two_pow_pos x)
  have hcr : c * 2^x + T % 2^x < 2^(x+1) := by
    have h4 : c * 2^x ≤ 1 * 2^x := Nat.mul_le_mul_right _ (by omega)
    rw [Nat.one_mul] at h4
    rw [Nat.pow_succ]
    omega
  have hN : (c * 2^x + T) / 2^(x+1) = T / 2^(x+1) := by
    generalize hhi : T / 2^(x+1) = hi at hTdecomp ⊢
    generalize hrr : T % 2^x = r at hTdecomp hcr
    rw [hTdecomp]
    rw [← Nat.add_assoc, Nat.add_comm (c * 2^x) (2^(x+1) * hi), Nat.add_assoc,
        Nat.mul_add_div (Nat.two_pow_pos (x+1)), Nat.div_eq_of_lt hcr, Nat.add_zero]
  have hdd : ∀ N : Nat, N / 2^j = N / 2^(x+1) / 2^(j-x-1) := by
    intro N
    rw [Nat.div_div_eq_div_mul, ← Nat.pow_add]
    congr 2
    omega
  rw [hdd (c * 2^x + T), hdd T, hN]

/-- ... and all three position cases packaged: bit j of c·2^x + T. -/
theorem bit_add_disjoint {c T x : Nat} (j : Nat) (hc : c < 2) (hT : T / 2^x % 2 = 0) :
    (c * 2^x + T) / 2^j % 2 = if j = x then c else T / 2^j % 2 := by
  rcases Nat.lt_trichotomy j x with hlt | heq | hgt
  · rw [if_neg (Nat.ne_of_lt hlt)]
    have hx : (2:Nat)^x = 2^(x-j) * 2^j := by
      rw [← Nat.pow_add]; congr 1; omega
    rw [hx, ← Nat.mul_assoc, Nat.add_comm, Nat.mul_comm (c * 2^(x-j)) (2^j)]
    rw [Nat.add_mul_div_left _ _ (Nat.two_pow_pos j)]
    have heven : c * 2^(x-j) = 2 * (c * 2^(x-j-1)) := by
      have h2p : (2:Nat)^(x-j) = 2 * 2^(x-j-1) := by
        rw [← Nat.pow_succ']
        congr 1
        omega
      rw [h2p, ← Nat.mul_assoc, Nat.mul_comm c 2, Nat.mul_assoc]
    rw [heven]
    generalize T / 2^j = u
    omega
  · subst heq
    rw [if_pos rfl, Nat.add_comm, Nat.mul_comm c (2^j)]
    rw [Nat.add_mul_div_left _ _ (Nat.two_pow_pos j)]
    generalize hu : T / 2^j = u
    rw [hu] at hT
    omega
  · rw [if_neg (Nat.ne_of_gt hgt)]
    exact bit_add_high hc hT hgt

/-- distinct scatter positions ⇒ absent positions read 0. -/
theorem bitsum_bit_notmem : ∀ (q : List Nat), q.Nodup → ∀ (n j : Nat), j ∉ q →
    bitsum q n / 2^j % 2 = 0
  | [], _, n, j, _ => by simp [bitsum]
  | x :: xs, hnd, n, j, hj => by
      have hx : x ∉ xs := (List.nodup_cons.mp hnd).1
      have hxs : xs.Nodup := (List.nodup_cons.mp hnd).2
      have hjx : j ≠ x := fun h => hj (h ▸ List.mem_cons_self ..)
      have hjxs : j ∉ xs := fun h => hj (List.mem_cons_of_mem x h)
      have hm2 : n % 2 < 2 := Nat.mod_lt n (by decide)
      have hT : bitsum xs (n/2) / 2^x % 2 = 0 := bitsum_bit_notmem xs hxs (n/2) x hx
      rw [show bitsum (x :: xs) n = n % 2 * 2^x + bitsum xs (n/2) from rfl]
      rw [bit_add_disjoint j hm2 hT, if_neg hjx]
      exact bitsum_bit_notmem xs hxs (n/2) j hjxs

/-- THE RELOCATION LEMMA: bit k of n reappears as bit q[k] of bitsum q n. -/
theorem bitsum_bit_getD : ∀ (q : List Nat), q.Nodup → ∀ (n k : Nat), k < q.length →
    bitsum q n / 2^(q.getD k 0) % 2 = n / 2^k % 2
  | [], _, _, k, h => by simp at h
  | x :: xs, hnd, n, 0, _ => by
      have hx : x ∉ xs := (List.nodup_cons.mp hnd).1
      have hm2 : n % 2 < 2 := Nat.mod_lt n (by decide)
      have hT : bitsum xs (n/2) / 2^x % 2 = 0 :=
        bitsum_bit_notmem xs (List.nodup_cons.mp hnd).2 (n/2) x hx
      rw [List.getD_cons_zero,
          show bitsum (x :: xs) n = n % 2 * 2^x + bitsum xs (n/2) from rfl,
          bit_add_disjoint x hm2 hT, if_pos rfl]
      simp
  | x :: xs, hnd, n, k+1, hk => by
      have hx : x ∉ xs := (List.nodup_cons.mp hnd).1
      have hxs : xs.Nodup := (List.nodup_cons.mp hnd).2
      have hklen : k < xs.length := by simpa using hk
      have hne : xs.getD k 0 ≠ x := fun h => hx (h ▸ getD_mem xs k hklen)
      have hm2 : n % 2 < 2 := Nat.mod_lt n (by decide)
      have hT : bitsum xs (n/2) / 2^x % 2 = 0 := bitsum_bit_notmem xs hxs (n/2) x hx
      rw [List.getD_cons_succ,
          show bitsum (x :: xs) n = n % 2 * 2^x + bitsum xs (n/2) from rfl,
          bit_add_disjoint (xs.getD k 0) hm2 hT, if_neg hne,
          bitsum_bit_getD xs hxs (n/2) k hklen]
      rw [Nat.div_div_eq_div_mul, ← Nat.pow_succ']

/-- per-bit xor: the xor'd bit is the disagreement indicator. Uses core's
    `Nat.testBit_xor` bridge; the bit-value analysis is a tiny 2×2 case
    split, disclosed. -/
theorem xor_bit (a b i : Nat) :
    (a ^^^ b) / 2^i % 2 = if a / 2^i % 2 = b / 2^i % 2 then 0 else 1 := by
  have hxor := Nat.testBit_xor a b i
  rw [Nat.testBit_eq_decide_div_mod_eq, Nat.testBit_eq_decide_div_mod_eq,
      Nat.testBit_eq_decide_div_mod_eq] at hxor
  have ha := Nat.mod_two_eq_zero_or_one (a / 2^i)
  have hb := Nat.mod_two_eq_zero_or_one (b / 2^i)
  have hab := Nat.mod_two_eq_zero_or_one ((a ^^^ b) / 2^i)
  rcases ha with ha | ha <;> rcases hb with hb | hb <;>
    rw [ha, hb] at hxor ⊢ <;> simp at hxor ⊢ <;> omega

theorem pc6_eq_bits (m : Nat) :
    pc6 m = ((List.range 6).map fun i => m / 2^i % 2).sum := by
  rw [show List.range 6 = [0,1,2,3,4,5] from rfl]
  simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  unfold pc6
  simp only [show (2:Nat)^0 = 1 from rfl, show (2:Nat)^1 = 2 from rfl,
    show (2:Nat)^2 = 4 from rfl, show (2:Nat)^3 = 8 from rfl,
    show (2:Nat)^4 = 16 from rfl, show (2:Nat)^5 = 32 from rfl, Nat.div_one]
  omega

/-- ham as the size of the disagreement set over the six bit positions. -/
theorem ham_eq_disagreements (a b : Nat) :
    ham a b = ((List.range 6).map fun i => if a / 2^i % 2 = b / 2^i % 2 then 0 else 1).sum := by
  show pc6 (a ^^^ b) = _
  rw [pc6_eq_bits]
  exact congrArg List.sum (List.map_congr_left fun i _ => xor_bit a b i)

/-- THE GENERAL ISOMETRY (classical coding theory — permuting coordinates is
    an isometry of the Hamming metric; standard, no novelty claimed): for ANY
    permutation p of the six bit positions and ALL naturals a, b,
    ham (applyPerm p a) (applyPerm p b) = ham a b. Structural proof — p
    carries the disagreement set of (a, b) bijectively onto that of
    (p·a, p·b); a bijection preserves cardinality. No case enumeration. -/
theorem applyPerm_isometry_perm (p : List Nat) (hp : p.Perm idp) (a b : Nat) :
    ham (applyPerm p a) (applyPerm p b) = ham a b := by
  have hlen : p.length = 6 := hp.length_eq
  have hnd : p.Nodup := hp.nodup_iff.mpr (by decide)
  have hp6 : p.Perm (List.range 6) := by
    rw [show List.range 6 = idp from rfl]; exact hp
  rw [ham_eq_disagreements, ham_eq_disagreements a b]
  have h1 : ((List.range 6).map fun j =>
        if applyPerm p a / 2^j % 2 = applyPerm p b / 2^j % 2 then 0 else 1).sum
      = (p.map fun j =>
        if applyPerm p a / 2^j % 2 = applyPerm p b / 2^j % 2 then 0 else 1).sum :=
    (sum_perm (hp6.map _)).symm
  have h2 : (p.map fun j =>
        if applyPerm p a / 2^j % 2 = applyPerm p b / 2^j % 2 then 0 else 1)
      = (List.range 6).map (fun i =>
        if applyPerm p a / 2^(p.getD i 0) % 2 = applyPerm p b / 2^(p.getD i 0) % 2
        then 0 else 1) := by
    rw [map_getD_comp p, hlen]
  have h3 : ((List.range 6).map (fun i =>
        if applyPerm p a / 2^(p.getD i 0) % 2 = applyPerm p b / 2^(p.getD i 0) % 2
        then 0 else 1))
      = (List.range 6).map (fun i => if a / 2^i % 2 = b / 2^i % 2 then 0 else 1) := by
    apply List.map_congr_left
    intro i hi
    have hip : i < p.length := by
      have := List.mem_range.mp hi; omega
    rw [applyPerm_eq_bitsum p hlen a, applyPerm_eq_bitsum p hlen b,
        bitsum_bit_getD p hnd a i hip, bitsum_bit_getD p hnd b i hip]
  rw [h1, h2, h3]

/- ------------- §1 finite group facts (kernel decide; applyPerm_isometry is
   derived from §0b's structural general isometry — zero native_decide) ------------- -/

theorem applyPerm_lt64 : ∀ p ∈ G48, ∀ h < 64, applyPerm p h < 64 := by decide

/-- Hamming isometry of the G48 action — derived by instantiating §0b's
    STRUCTURAL general lemma (`applyPerm_isometry_perm`; G48 ⊆ perms idp by
    construction, and members of `perms l` are permutations of l —
    `mem_perms_perm`). The `< 64` bounds are retained verbatim for downstream
    compatibility; the proof does not need them. Until 2026-08-04 this was the
    file's one remaining `native_decide` (48 × 64 × 64 compiled-evaluator
    checks; the 2026-07-22 header note recorded kernel-`decide` exhaustion on
    that ENUMERATION route — accurate then, but moot now: the structural proof
    enumerates nothing), so #68's wdTerm/transitions/budget leg and
    pruneV4_mapP no longer inherit any compiler trust. -/
theorem applyPerm_isometry :
    ∀ p ∈ G48, ∀ a < 64, ∀ b < 64, ham (applyPerm p a) (applyPerm p b) = ham a b := by
  intro p hp a _ b _
  exact applyPerm_isometry_perm p (mem_perms_perm (List.mem_filter.mp hp).1) a b

theorem applyPerm_comp63 :
    ∀ p ∈ G48, ∀ h < 64, applyPerm p h ^^^ 63 = applyPerm p (h ^^^ 63) := by
  decide

theorem applyPerm_partner :
    ∀ p ∈ G48, ∀ h < 64, applyPerm p (partner h) = partner (applyPerm p h) := by
  decide

theorem applyPerm_range_perm :
    ∀ p ∈ G48, ((List.range 64).map (applyPerm p)).isPerm (List.range 64) = true := by
  decide

/-- injectivity on 6-bit values — derived structurally from
    `applyPerm_range_perm` (kernel-checked): the image of range 64 is a
    permutation of range 64, hence duplicate-free, and equal images at
    distinct indices would contradict Nodup. Replaces the prior direct
    native_decide check (a 48 × 64 × 64 kernel `decide` is out of reach, but
    this derivation needs only the 48 × isPerm fact above). -/
theorem applyPerm_inj :
    ∀ p ∈ G48, ∀ a < 64, ∀ b < 64, (applyPerm p a = applyPerm p b ↔ a = b) := by
  intro p hp a ha b hb
  refine ⟨fun he => ?_, fun he => by rw [he]⟩
  have hpm : ((List.range 64).map (applyPerm p)).Perm (List.range 64) :=
    List.isPerm_iff.mp (applyPerm_range_perm p hp)
  have hnd : ((List.range 64).map (applyPerm p)).Nodup :=
    hpm.nodup_iff.mpr List.nodup_range
  have hla : a < ((List.range 64).map (applyPerm p)).length := by simpa using ha
  have hlb : b < ((List.range 64).map (applyPerm p)).length := by simpa using hb
  have hga : ((List.range 64).map (applyPerm p))[a]'hla = applyPerm p a := by simp
  have hgb : ((List.range 64).map (applyPerm p))[b]'hlb = applyPerm p b := by simp
  exact (List.getElem_inj hnd).mp (by rw [hga, hgb]; exact he)

theorem partner_involution : ∀ h < 64, partner (partner h) = h ∧ partner h < 64 := by
  decide

theorem xor63_lt64 : ∀ h < 64, h ^^^ 63 < 64 := by decide

/- ------------- §2 list utilities (core-Lean, no mathlib) ------------- -/

-- (sum_perm moved to §0b, 2026-08-04 — the isometry layer needs it earlier.)

theorem findIdx_congr {l : List Nat} {p q : Nat → Bool}
    (h : ∀ x ∈ l, p x = q x) : l.findIdx p = l.findIdx q := by
  induction l with
  | nil => rfl
  | cons a t ih =>
    rw [List.findIdx_cons, List.findIdx_cons, h a (by simp),
        ih (fun x hx => h x (List.mem_cons_of_mem a hx))]

/-- position of σh in σ·l = position of h in l (restated from Automorphism.lean). -/
theorem findIdx_mapP (p : List Nat) (hp : p ∈ G48) {l : List Nat}
    (hb : ∀ x ∈ l, x < 64) {h : Nat} (hh : h < 64) :
    (l.map (applyPerm p)).findIdx (· == applyPerm p h) = l.findIdx (· == h) := by
  rw [List.findIdx_map]
  apply findIdx_congr
  intro x hx
  have hx64 := hb x hx
  simp only [Function.comp]
  rw [Bool.eq_iff_iff]
  simp only [beq_iff_eq]
  exact applyPerm_inj p hp x hx64 h hh

/-- membership transfers along the relabeling (σ injective on 6-bit values). -/
theorem mem_mapP (p : List Nat) (hp : p ∈ G48) {l : List Nat}
    (hb : ∀ x ∈ l, x < 64) {v : Nat} (hv : v < 64) :
    applyPerm p v ∈ l.map (applyPerm p) ↔ v ∈ l := by
  constructor
  · intro h
    obtain ⟨x, hx, he⟩ := List.mem_map.mp h
    exact ((applyPerm_inj p hp x (hb x hx) v hv).mp he) ▸ hx
  · intro h
    exact List.mem_map.mpr ⟨v, h, rfl⟩

/-- the reindexing engine: a sum over the 64 hexagram values is unchanged when
    the summand at σv on one side equals the summand at v on the other —
    because σ permutes range 64 (the c3x64_mapP pattern of Automorphism.lean). -/
theorem sum_reindex_mapP (p : List Nat) (hp : p ∈ G48) (F G : Nat → Nat)
    (hFG : ∀ v < 64, F (applyPerm p v) = G v) :
    ((List.range 64).map F).sum = ((List.range 64).map G).sum := by
  have hpm : ((List.range 64).map (applyPerm p)).Perm (List.range 64) :=
    List.isPerm_iff.mp (applyPerm_range_perm p hp)
  have h1 : (((List.range 64).map (applyPerm p)).map F).sum =
      ((List.range 64).map F).sum := sum_perm (hpm.map F)
  rw [← h1, List.map_map]
  apply congrArg
  apply List.map_congr_left
  intro v hv
  exact hFG v (List.mem_range.mp hv)

/-- the transition list is unchanged by any σ ∈ G48 (Hamming isometry;
    restated from Automorphism.lean — feeds #68's budget invariance). -/
theorem transitions_mapP (p : List Nat) (hp : p ∈ G48) {l : List Nat}
    (hb : ∀ x ∈ l, x < 64) :
    transitions (l.map (applyPerm p)) = transitions l := by
  unfold transitions
  rw [← List.map_tail, List.zip_map, List.map_map]
  apply List.map_congr_left
  intro ab hab
  have hmem := List.of_mem_zip hab
  have ha : ab.1 < 64 := hb _ hmem.1
  have hb2 : ab.2 < 64 := hb _ (List.mem_of_mem_tail hmem.2)
  simp [Prod.map, applyPerm_isometry p hp _ ha _ hb2]

/-- congruence for `if` under an iff of (decidable) conditions — core Lean's
    `if_congr` is not available on this toolchain, so it is proved here. -/
theorem if_congr' {c₁ c₂ : Prop} [Decidable c₁] [Decidable c₂] {a b x y : Nat}
    (hc : c₁ ↔ c₂) (hx : a = x) (hy : b = y) :
    (if c₁ then a else b) = (if c₂ then x else y) := by
  by_cases h : c₂
  · rw [if_pos (hc.mpr h), if_pos h, hx]
  · rw [if_neg (fun hh => h (hc.mp hh)), if_neg h, hy]

/- ------------- §3 the model of the DFS-state quantities the prunes read ------------- -/

/-- per-hexagram contribution to the partial complement distance: if h and its
    complement are both placed in the prefix, the gap between their positions;
    else 0. (Positions via findIdx, the convention of KingWen.lean's c3x64.) -/
def cdTerm (seq : List Nat) (v : Nat) : Nat :=
  if v ∈ seq ∧ (v ^^^ 63) ∈ seq then
    max (seq.findIdx (· == v)) (seq.findIdx (· == (v ^^^ 63))) -
      min (seq.findIdx (· == v)) (seq.findIdx (· == (v ^^^ 63)))
  else 0

/-- #67's partial complement distance = solve.c's mw_partial_cd_x64: summing
    cdTerm over all 64 hexagrams counts each fully-placed unordered complement
    pair twice — exactly the ×2 of compute_comp_dist_x64's convention. -/
def partialCd (seq : List Nat) : Nat := ((List.range 64).map (cdTerm seq)).sum

/-- per-hexagram indicator that its complement pair is NOT yet fully placed. -/
def inevTerm (seq : List Nat) (v : Nat) : Nat :=
  if v ∈ seq ∧ (v ^^^ 63) ∈ seq then 0 else 1

/-- #70's optimistic completion bound = solve.c's
    mw_inevitable_remaining_cd_x64: each not-both-placed complement pair is
    counted at v and at v⊕63, giving 2 × (#unfinished pairs). -/
def inevitableBound (seq : List Nat) : Nat := ((List.range 64).map (inevTerm seq)).sum

/-- per-hexagram indicator that h's C1 partner pair is unplaced and demands
    within-pair distance class d. -/
def wdTerm (seq : List Nat) (d : Nat) (h : Nat) : Nat :=
  if h ∉ seq ∧ partner h ∉ seq ∧ ham h (partner h) = d then 1 else 0

/-- #68's per-class demand, doubled: counting hexagrams instead of unordered
    partner pairs gives unusedWd2 seq d = 2 × solve.c's unused_wd_count[d]
    (each unplaced pair {h, partner h} is counted at h and at partner h;
    ham and unplacedness are symmetric under h ↦ partner h). -/
def unusedWd2 (seq : List Nat) (d : Nat) : Nat := ((List.range 64).map (wdTerm seq d)).sum

/-- #68's remaining per-class budget: the exact C5 distribution target minus
    the class-d transitions already consumed by the prefix — solve.c maintains
    budget[] by exactly one decrement per consumed transition. -/
def budgetOf (target : Nat → Nat) (seq : List Nat) (d : Nat) : Nat :=
  target d - (transitions seq).count d

/- ------------- §4 the prune predicates (model level) ------------- -/

/-- #67: partial complement distance already exceeds the threshold
    (kw_comp_dist_x64 = 776 in solve.c; kept generic here). -/
def prune67 (thresh : Nat) (seq : List Nat) : Bool := decide (thresh < partialCd seq)

/-- #67+#70 combined (the live predicate in solve.c): partial + inevitable
    future contribution exceeds the threshold. -/
def prune70 (thresh : Nat) (seq : List Nat) : Bool :=
  decide (thresh < partialCd seq + inevitableBound seq)

/-- #68: some distance class's unplaced demand exceeds its remaining budget.
    Both sides doubled relative to solve.c (equivalent: budget[d] < n ⟺
    2·budget[d] < 2n, and unusedWd2 = 2 × unused_wd_count[d]). -/
def prune68 (target : Nat → Nat) (seq : List Nat) : Bool :=
  (List.range 7).any fun d => decide (2 * budgetOf target seq d < unusedWd2 seq d)

/-- the full v4 prune-stack predicate: prune iff #67+#70 or #68 fires
    (#67 alone is subsumed by #70, whose bound is ≥ 0). -/
def pruneV4 (target : Nat → Nat) (thresh : Nat) (seq : List Nat) : Bool :=
  prune70 thresh seq || prune68 target seq

/- ------------- §5 pointwise transfer of each quantity along σ ------------- -/

theorem cdTerm_mapP (p : List Nat) (hp : p ∈ G48) {seq : List Nat}
    (hb : ∀ x ∈ seq, x < 64) {v : Nat} (hv : v < 64) :
    cdTerm (seq.map (applyPerm p)) (applyPerm p v) = cdTerm seq v := by
  unfold cdTerm
  rw [applyPerm_comp63 p hp v hv]
  exact if_congr'
    (and_congr (mem_mapP p hp hb hv) (mem_mapP p hp hb (xor63_lt64 v hv)))
    (by rw [findIdx_mapP p hp hb hv, findIdx_mapP p hp hb (xor63_lt64 v hv)])
    rfl

theorem inevTerm_mapP (p : List Nat) (hp : p ∈ G48) {seq : List Nat}
    (hb : ∀ x ∈ seq, x < 64) {v : Nat} (hv : v < 64) :
    inevTerm (seq.map (applyPerm p)) (applyPerm p v) = inevTerm seq v := by
  unfold inevTerm
  rw [applyPerm_comp63 p hp v hv]
  exact if_congr'
    (and_congr (mem_mapP p hp hb hv) (mem_mapP p hp hb (xor63_lt64 v hv)))
    rfl rfl

theorem wdTerm_mapP (p : List Nat) (hp : p ∈ G48) {seq : List Nat}
    (hb : ∀ x ∈ seq, x < 64) (d : Nat) {h : Nat} (hh : h < 64) :
    wdTerm (seq.map (applyPerm p)) d (applyPerm p h) = wdTerm seq d h := by
  have hp64 : partner h < 64 := (partner_involution h hh).2
  unfold wdTerm
  rw [← applyPerm_partner p hp h hh]
  exact if_congr'
    (and_congr (not_congr (mem_mapP p hp hb hh))
      (and_congr (not_congr (mem_mapP p hp hb hp64))
        (by rw [applyPerm_isometry p hp h hh (partner h) hp64])))
    rfl rfl

/-- #67's quantity is G-invariant: relabeling preserves the partial
    complement-distance sum (positions unchanged, complement pairs mapped to
    complement pairs, index set permuted). -/
theorem partialCd_mapP (p : List Nat) (hp : p ∈ G48) {seq : List Nat}
    (hb : ∀ x ∈ seq, x < 64) :
    partialCd (seq.map (applyPerm p)) = partialCd seq := by
  unfold partialCd
  exact sum_reindex_mapP p hp _ _ (fun v hv => cdTerm_mapP p hp hb hv)

/-- #70's quantity is G-invariant: the count of unfinished complement pairs
    is preserved. -/
theorem inevitableBound_mapP (p : List Nat) (hp : p ∈ G48) {seq : List Nat}
    (hb : ∀ x ∈ seq, x < 64) :
    inevitableBound (seq.map (applyPerm p)) = inevitableBound seq := by
  unfold inevitableBound
  exact sum_reindex_mapP p hp _ _ (fun v hv => inevTerm_mapP p hp hb hv)

/-- #68's demand is G-invariant: within-pair distance classes of unplaced
    pairs are preserved (isometry + partner-commutation). -/
theorem unusedWd2_mapP (p : List Nat) (hp : p ∈ G48) {seq : List Nat}
    (hb : ∀ x ∈ seq, x < 64) (d : Nat) :
    unusedWd2 (seq.map (applyPerm p)) d = unusedWd2 seq d := by
  unfold unusedWd2
  exact sum_reindex_mapP p hp _ _ (fun h hh => wdTerm_mapP p hp hb d hh)

/-- #68's budget is G-invariant: the transition multiset of the prefix is
    literally unchanged (Hamming isometry), for any budget target. -/
theorem budgetOf_mapP (target : Nat → Nat) (p : List Nat) (hp : p ∈ G48)
    {seq : List Nat} (hb : ∀ x ∈ seq, x < 64) (d : Nat) :
    budgetOf target (seq.map (applyPerm p)) d = budgetOf target seq d := by
  unfold budgetOf
  rw [transitions_mapP p hp hb]

/- ------------- §6 THE INVARIANCE THEOREMS: prune(σ·s) = prune(s) ------------- -/

theorem prune67_mapP (thresh : Nat) (p : List Nat) (hp : p ∈ G48)
    {seq : List Nat} (hb : ∀ x ∈ seq, x < 64) :
    prune67 thresh (seq.map (applyPerm p)) = prune67 thresh seq := by
  unfold prune67
  rw [partialCd_mapP p hp hb]

theorem prune70_mapP (thresh : Nat) (p : List Nat) (hp : p ∈ G48)
    {seq : List Nat} (hb : ∀ x ∈ seq, x < 64) :
    prune70 thresh (seq.map (applyPerm p)) = prune70 thresh seq := by
  unfold prune70
  rw [partialCd_mapP p hp hb, inevitableBound_mapP p hp hb]

theorem prune68_mapP (target : Nat → Nat) (p : List Nat) (hp : p ∈ G48)
    {seq : List Nat} (hb : ∀ x ∈ seq, x < 64) :
    prune68 target (seq.map (applyPerm p)) = prune68 target seq := by
  unfold prune68
  have hfun : (fun d => decide (2 * budgetOf target (seq.map (applyPerm p)) d <
        unusedWd2 (seq.map (applyPerm p)) d)) =
      (fun d => decide (2 * budgetOf target seq d < unusedWd2 seq d)) := by
    funext d
    rw [budgetOf_mapP target p hp hb d, unusedWd2_mapP p hp hb d]
  rw [hfun]

/-- the full v4 prune stack is G-invariant. -/
theorem pruneV4_mapP (target : Nat → Nat) (thresh : Nat) (p : List Nat)
    (hp : p ∈ G48) {seq : List Nat} (hb : ∀ x ∈ seq, x < 64) :
    pruneV4 target thresh (seq.map (applyPerm p)) = pruneV4 target thresh seq := by
  unfold pruneV4
  rw [prune70_mapP thresh p hp hb, prune68_mapP target p hp hb]

/- ------------- §7 packaging: invariant prune ⇒ orbit-invariant work ------------- -/

/-- fuel-indexed node count of the tree generated by a children function
    (fuel ≥ walk depth ⇒ this is the true node count; the DFS depth is ≤ 32). -/
def treeCount {α : Type} (children : α → List α) : Nat → α → Nat
  | 0, _ => 1
  | fuel+1, s => 1 + ((children s).map (treeCount children fuel)).sum

/-- a state bijection that commutes with the children function UP TO
    PERMUTATION of the children list preserves node counts. (Order is
    deliberately not required: node count — and hence work min(tree,B) —
    is independent of sibling order.) -/
theorem treeCount_equivariant {α : Type} (children : α → List α) (f : α → α)
    (hc : ∀ s, (children (f s)).Perm ((children s).map f)) :
    ∀ (fuel : Nat) (s : α), treeCount children fuel (f s) = treeCount children fuel s := by
  intro fuel
  induction fuel with
  | zero => intro s; rfl
  | succ n ih =>
    intro s
    simp only [treeCount]
    have h1 : ((children (f s)).map (treeCount children n)).sum =
        (((children s).map f).map (treeCount children n)).sum :=
      sum_perm ((hc s).map (treeCount children n))
    rw [h1, List.map_map]
    have h2 : (children s).map (treeCount children n ∘ f) =
        (children s).map (treeCount children n) :=
      List.map_congr_left (fun x _ => ih x)
    rw [h2]

/-- the DFS children function: prune kills the node, else expand. -/
def pruneChildren {α : Type} (prune : α → Bool) (expand : α → List α) (s : α) :
    List α :=
  if prune s then [] else expand s

theorem pruneChildren_equivariant {α : Type} (prune : α → Bool)
    (expand : α → List α) (f : α → α)
    (hprune : ∀ s, prune (f s) = prune s)
    (hexpand : ∀ s, (expand (f s)).Perm ((expand s).map f)) :
    ∀ s, (pruneChildren prune expand (f s)).Perm
      ((pruneChildren prune expand s).map f) := by
  intro s
  unfold pruneChildren
  rw [hprune s]
  cases hps : prune s with
  | true => simp
  | false => simpa using hexpand s

/-- GENERIC WORK INVARIANCE: prune invariant + expansion equivariant (up to
    child order) ⇒ per-cell work min(tree, B) is equal at σ-corresponding
    roots, for EVERY node budget B. This is the "hence" of the ×36 orbit
    argument: full cost Σ_cells min(tree,B) = |orbit| × Σ_reps min(tree,B). -/
theorem work_orbit_invariant {α : Type} (prune : α → Bool)
    (expand : α → List α) (f : α → α)
    (hprune : ∀ s, prune (f s) = prune s)
    (hexpand : ∀ s, (expand (f s)).Perm ((expand s).map f))
    (fuel B : Nat) (s : α) :
    min (treeCount (pruneChildren prune expand) fuel (f s)) B =
      min (treeCount (pruneChildren prune expand) fuel s) B := by
  rw [treeCount_equivariant (pruneChildren prune expand) f
    (pruneChildren_equivariant prune expand f hprune hexpand) fuel s]

/-- search states: placed prefixes over the 64 hexagram values. -/
abbrev State64 := {s : List Nat // ∀ x ∈ s, x < 64}

/-- the action of σ ∈ G48 on search states. -/
def mapState (p : List Nat) (hp : p ∈ G48) (s : State64) : State64 :=
  ⟨s.val.map (applyPerm p), by
    intro x hx
    obtain ⟨y, hy, rfl⟩ := List.mem_map.mp hx
    exact applyPerm_lt64 p hp y (s.property y hy)⟩

/-- CONCRETE COROLLARY for the v4 prune stack: with the machine-checked
    G-invariance of #67/#68/#70 discharged, per-cell work min(tree, B) is
    orbit-invariant for any expansion step that commutes with relabeling up
    to child order — the single remaining bridge hypothesis `he`, whose
    empirical witness is test-plan T1.6 (node-count equality across a full
    orbit with the final predicate set). -/
theorem pruneV4_work_invariant (target : Nat → Nat) (thresh : Nat)
    (p : List Nat) (hp : p ∈ G48) (expand : State64 → List State64)
    (he : ∀ s, (expand (mapState p hp s)).Perm ((expand s).map (mapState p hp)))
    (fuel B : Nat) (s : State64) :
    min (treeCount (pruneChildren (fun t => pruneV4 target thresh t.val) expand)
      fuel (mapState p hp s)) B =
    min (treeCount (pruneChildren (fun t => pruneV4 target thresh t.val) expand)
      fuel s) B := by
  apply work_orbit_invariant (fun t => pruneV4 target thresh t.val) expand
    (mapState p hp) _ he fuel B s
  intro t
  exact pruneV4_mapP target thresh p hp t.property

/- ------------- §8 sanity instantiations (decide +kernel spot checks; migrated from native_decide 2026-08-04) ------------- -/

/-- the exact C5 distribution {1:2, 2:20, 3:13, 4:19, 6:9} (SPECIFICATION.md). -/
def c5target : Nat → Nat := fun d =>
  if d = 1 then 2 else if d = 2 then 20 else if d = 3 then 13 else
    if d = 4 then 19 else if d = 6 then 9 else 0

/-- the action moves states (invariance is not vacuous). -/
example : ∃ p ∈ G48, [63, 0, 17, 34, 23, 58].map (applyPerm p) ≠
    [63, 0, 17, 34, 23, 58] := by decide +kernel
/-- #67/#70 quantities across the WHOLE group on a King Wen prefix:
    only the complement pair {63, 0} is fully placed (at gap 1, counted at
    both members ⇒ partialCd = 2); the other 31 pairs are unfinished, so
    inevitableBound counts their 62 member hexagrams. -/
example : ∀ p ∈ G48,
    partialCd ([63, 0, 17, 34, 23, 58].map (applyPerm p)) = 2 := by decide +kernel
example : ∀ p ∈ G48,
    inevitableBound ([63, 0, 17, 34, 23, 58].map (applyPerm p)) = 62 := by
  decide +kernel
/-- full predicate agreement across the whole group (a computed instance of
    pruneV4_mapP). -/
example : ∀ p ∈ G48,
    pruneV4 c5target 776 ([63, 0, 17, 34, 23, 58].map (applyPerm p)) =
      pruneV4 c5target 776 [63, 0, 17, 34, 23, 58] := by decide +kernel
/-- the predicates are not vacuously false: zero budget with 32 unplaced
    pairs fires #68 ... -/
example : prune68 (fun _ => 0) [] = true := by decide +kernel
/-- ... while the real C5 budget does not fire at the root (KW exists). -/
example : prune68 c5target [] = false := by decide +kernel
example : pruneV4 c5target 776 [] = false := by decide +kernel
/- ------------- §9 prefix-G (running-G) invariance — the C3 G-channel DP
   quotient-compatibility (design §1.2/§2.5; review §1.4/§3 item 1) -------------

   The C3 G-channel design (roae-private DESIGN_C3_GCHANNEL_2026_07_21.md)
   augments the exact-counting DP state with running-G, accumulated walking
   pair placements in slot order: placing pair P at slot s does nothing if P
   is self-complement, g −= s if P OPENS a couple (complement-partner pair
   not yet placed), g += s if P CLOSES one (partner pair already placed).
   Design §1.2 claims (prose) that running-G "rides the canonical-mask
   quotient exactly like rid" — i.e. is invariant under the 48-group's value
   relabeling of a placement prefix — and §2.5 promised the corollary in
   Lean. This section is that lemma. The argument: σ ∈ G48 acts on hexagram
   VALUES only (slots/indices are untouched), commutes with complement
   (applyPerm_comp63) and with the C1 pairing (applyPerm_partner), and is
   injective on 6-bit values (applyPerm_inj) — so each placement's
   self/open/close status is preserved and every ±s term is preserved
   slotwise. Sum preserved term-by-term; no reindexing is even needed
   (contrast partialCd_mapP, which reindexes over hexagram values).

   Model: a placement prefix is a `List Nat` of placed-pair REPRESENTATIVES
   (either member; one per slot, in slot order), the first element sitting
   at slot s0 — s0 is kept general, covering both the production convention
   (anchor pair {0, 63} pinned at slot 0, free walk starting at s0 = 1) and
   whole-walk accounting from slot 0 (the anchor is self-complement, so
   including it adds 0 — see the KW witness below).

   Trust base: kernel-only — the chain uses applyPerm_comp63/partner
   (kernel decide) and applyPerm_inj (structural, from the kernel-checked
   applyPerm_range_perm); no native_decide anywhere in this section.
   Bridge facts (stated, NOT machine-checked — the same discipline as the
   file header's list): solve.c's g accumulator equals this model's
   runningG (one partner_pair mask test per placement), and at a full mask
   runningG equals the final G = Σ_couples |slot − slot| of
   C3Decomposition.c3slot (witnessed at KW below and carried by runtime
   gates G1/G4/G5 of the design). Attribution: gap identified by the C3
   adversarial review (REVIEW_C3_FABLE_2026_07_22.md); formalization
   Claude (Fable 5), 2026-07-22. No novelty claimed (elementary invariance;
   corrections welcome). -/

/-- b is a member of the C1 pair through a (the pair {a, partner a}). -/
def inPair (a b : Nat) : Bool := b == a || b == partner a

/-- the pair through h is self-complement: h's complement lies in h's own
    pair (h ⊕ 63 = h is impossible, so this means partner h = h ⊕ 63). -/
def selfPaired (h : Nat) : Bool := inPair h (h ^^^ 63)

/-- the complement-partner pair of h's pair is already placed: some placed
    representative lies in the pair through h ⊕ 63. -/
def partnerPlaced (pre : List Nat) (h : Nat) : Bool := pre.any (inPair (h ^^^ 63))

/-- the running-G increment of placing pair-representative h at slot s given
    the previously placed representatives `pre` (design §1.1): self-pair 0,
    close +s, open −s. -/
def gStep (pre : List Nat) (h : Nat) (s : Nat) : Int :=
  if selfPaired h then 0 else if partnerPlaced pre h then (s : Int) else -(s : Int)

/-- running-G of the placement walk `ps` starting at slot s: the DP's g
    accumulator, processing placements in slot order. -/
def runningGAux (s : Nat) (pre : List Nat) : List Nat → Int
  | [] => 0
  | h :: rest => gStep pre h s + runningGAux (s + 1) (pre ++ [h]) rest

/-- running-G of a full or partial placement prefix, first element at slot s0. -/
def runningG (s0 : Nat) (ps : List Nat) : Int := runningGAux s0 [] ps

/-- pair membership transfers along σ (injectivity + pairing-commutation). -/
theorem inPair_mapP (p : List Nat) (hp : p ∈ G48) {a b : Nat}
    (ha : a < 64) (hb : b < 64) :
    inPair (applyPerm p a) (applyPerm p b) = inPair a b := by
  unfold inPair
  rw [← applyPerm_partner p hp a ha]
  have h1 : (applyPerm p b == applyPerm p a) = (b == a) := by
    rw [Bool.eq_iff_iff]
    simp only [beq_iff_eq]
    exact applyPerm_inj p hp b hb a ha
  have h2 : (applyPerm p b == applyPerm p (partner a)) = (b == partner a) := by
    rw [Bool.eq_iff_iff]
    simp only [beq_iff_eq]
    exact applyPerm_inj p hp b hb (partner a) (partner_involution a ha).2
  rw [h1, h2]

/-- self-complement status of a pair is preserved (σ commutes with ⊕63). -/
theorem selfPaired_mapP (p : List Nat) (hp : p ∈ G48) {h : Nat} (hh : h < 64) :
    selfPaired (applyPerm p h) = selfPaired h := by
  unfold selfPaired
  rw [applyPerm_comp63 p hp h hh]
  exact inPair_mapP p hp hh (xor63_lt64 h hh)

/-- Bool.any congruence (pointwise-equal predicates; core has no any_congr
    on this toolchain, mirroring findIdx_congr above). -/
theorem any_congr {l : List Nat} {p q : Nat → Bool}
    (h : ∀ x ∈ l, p x = q x) : l.any p = l.any q := by
  induction l with
  | nil => rfl
  | cons a t ih =>
    rw [List.any_cons, List.any_cons, h a (by simp),
        ih (fun x hx => h x (List.mem_cons_of_mem a hx))]

/-- open/close status is preserved: the partner pair of σh is placed in the
    σ-image prefix iff the partner pair of h is placed in the prefix. -/
theorem partnerPlaced_mapP (p : List Nat) (hp : p ∈ G48) {pre : List Nat}
    (hb : ∀ x ∈ pre, x < 64) {h : Nat} (hh : h < 64) :
    partnerPlaced (pre.map (applyPerm p)) (applyPerm p h) = partnerPlaced pre h := by
  unfold partnerPlaced
  rw [applyPerm_comp63 p hp h hh, List.any_map]
  exact any_congr (fun x hx => inPair_mapP p hp (xor63_lt64 h hh) (hb x hx))

/-- each placement's ±s increment is preserved slotwise. -/
theorem gStep_mapP (p : List Nat) (hp : p ∈ G48) {pre : List Nat}
    (hb : ∀ x ∈ pre, x < 64) {h : Nat} (hh : h < 64) (s : Nat) :
    gStep (pre.map (applyPerm p)) (applyPerm p h) s = gStep pre h s := by
  unfold gStep
  rw [selfPaired_mapP p hp hh, partnerPlaced_mapP p hp hb hh]

theorem runningGAux_mapP (p : List Nat) (hp : p ∈ G48) :
    ∀ (ps pre : List Nat) (s : Nat), (∀ x ∈ pre, x < 64) → (∀ x ∈ ps, x < 64) →
      runningGAux s (pre.map (applyPerm p)) (ps.map (applyPerm p)) =
        runningGAux s pre ps := by
  intro ps
  induction ps with
  | nil => intro pre s _ _; rfl
  | cons h rest ih =>
    intro pre s hbpre hbcons
    have hh : h < 64 := hbcons h (List.mem_cons_self ..)
    simp only [List.map_cons, runningGAux]
    rw [gStep_mapP p hp hbpre hh s]
    have happ : pre.map (applyPerm p) ++ [applyPerm p h] =
        (pre ++ [h]).map (applyPerm p) := by
      rw [List.map_append, List.map_cons, List.map_nil]
    rw [happ, ih (pre ++ [h]) (s + 1)
      (fun x hx => by
        rcases List.mem_append.mp hx with hxp | hxh
        · exact hbpre x hxp
        · rw [List.mem_singleton.mp hxh]; exact hh)
      (fun x hx => hbcons x (List.mem_cons_of_mem h hx))]

/-- PREFIX-G G48-INVARIANCE (the design §1.2/§2.5 lemma): relabeling a
    placement prefix by any σ ∈ G48 preserves running-G — for every start
    slot, hence at every layer of the DP. Running-G therefore rides the
    canonical-mask quotient exactly like rid, and the gather step needs no
    per-group-element G recomputation. -/
theorem runningG_mapP (p : List Nat) (hp : p ∈ G48) (s0 : Nat) {ps : List Nat}
    (hb : ∀ x ∈ ps, x < 64) :
    runningG s0 (ps.map (applyPerm p)) = runningG s0 ps :=
  runningGAux_mapP p hp ps [] s0 (fun _ hx => absurd hx (List.not_mem_nil)) hb

/-- packaging on search states, matching §7's mapState action. -/
theorem runningG_orbit_invariant (p : List Nat) (hp : p ∈ G48) (s0 : Nat)
    (s : State64) :
    runningG s0 (mapState p hp s).val = runningG s0 s.val :=
  runningG_mapP p hp s0 s.property

/- §9 sanity witnesses (kernel decide — cheap enough for the elaborator's
   evaluator; §8's heavier instances use decide +kernel). -/

/-- KW's 32 pair representatives in slot order (even positions of KW; slot 0
    = the self-complement anchor pair {63, 0}, contributing 0 to G). -/
def kwPairReps : List Nat :=
  [63, 17, 23, 2, 55, 7, 61, 4, 25, 3, 41, 32, 57, 33, 18, 28,
   60, 40, 53, 20, 35, 31, 24, 26, 29, 9, 52, 13, 54, 50, 51, 21]

/-- KW witness (runtime gate G4's model side): running-G accumulated along
    KW's full pair walk equals 95 = C3Decomposition.kw_slot_sum_95, i.e.
    C3 = 16 + 8·95 = 776. -/
example : runningG 0 kwPairReps = 95 := by decide

/-- computed instance of `runningG_mapP` across the WHOLE group on the KW
    walk: every σ-relabeled prefix accumulates the same G = 95. -/
example : ∀ p ∈ G48, runningG 0 (kwPairReps.map (applyPerm p)) = 95 := by decide

/-- the action moves the walk (the instance above is not vacuous). -/
example : ∃ p ∈ G48, kwPairReps.map (applyPerm p) ≠ kwPairReps := by decide

end PruneGInvariance

/-! ### Axiom audit (added 2026-08-01)
Emits the trust base for every theorem in this file that is CITED BY NAME in the
public documentation, so the suite's `#print axioms` claims are OBSERVED rather than
statically inferred. Expected: `[propext, Classical.choice, Quot.sound]`, or
`[propext]` alone for the finite facts. Any `Lean.ofReduceBool` here means a
`native_decide` (compiler trust) is load-bearing and the docs must say so.
(On leanprover/lean4:v4.31.0 a `native_decide` proof instead surfaces under `#print axioms` as an
auxiliary axiom named `<decl>._native.native_decide.ax_*`, NOT as `Lean.ofReduceBool` — measured
2026-09-04. So the ABSENCE of `Lean.ofReduceBool` is not a sufficient tell; the sound check is the
ALLOWLIST: any axiom token outside [propext, Classical.choice, Quot.sound] fails the audit.) -/
#print axioms PruneGInvariance.applyPerm_isometry_perm
#print axioms PruneGInvariance.applyPerm_isometry
#print axioms PruneGInvariance.partner_involution
#print axioms PruneGInvariance.sum_perm
#print axioms PruneGInvariance.transitions_mapP
