-- https://github.com/petersm3/roae
-- Developed with AI assistance (Claude, Anthropic)
/-
  TrigramTheorems.lean — machine-checked trigram-level structure of the ROAE
  constraint system (2026-07-11).

  *** COMPILES CLEAN on Lean 4.31.0 (2026-07-11; re-verified 2026-08-07 on
  *** the kernel-only revision, x86_64 linux, core only —
  *** no mathlib, no lake project): `lean TrigramTheorems.lean` exits 0
  *** with zero errors/warnings; zero `sorry`, zero `axiom`, zero `admit`.
  *** The pinned toolchain is recorded in this directory's `lean-toolchain`
  *** (leanprover/lean4:v4.31.0). Written per the private scoping doc
  *** (roae-private TRIGRAM_ANALYSIS_SCOPING_2026_07_11, TG-1..TG-5 asset
  *** tier); every statement below was verified numerically in Python
  *** (all-64 / all-4096 / all-720 exhaustive checks) BEFORE being drafted
  *** in Lean, and the two-language check is repeatable via
  *** `python3 solve.py --trigram-verify`. Promoted from the private staging
  *** draft 2026-07-11 (operator-approved); prose companion:
  *** documentation/TRIGRAM_STRUCTURE.md.

  Core Lean 4 only (no mathlib, no lake). Standalone: definitions restated
  verbatim from KingWen.lean / Automorphism.lean, per the repo's established
  one-file-per-theorem-suite pattern.

  Trust base (updated 2026-08-07, per the standing native_decide → decide
  migration policy in lean/README.md): kernel-only end to end — ZERO
  native_decide anywhere in this file. History: on 2026-07-27 the
  pairdist_count_* / TG-1 count / selfcomp_pair lemmas migrated
  native_decide → kernel `decide`, making the TG-2 lead theorems and the
  TG-1 counts kernel-only; on 2026-08-07 the remaining §4a–§6 finite facts
  (the TG-3/TG-4/TG-5 subgroup facts and the §6 sanity instances) migrated
  native_decide → `decide +kernel` (kernel-evaluated, no compiler trust),
  and the one obligation too large for either enumeration route — §4c's
  blockPreserving_iff_blockwise, whose direct 720-permutation kernel
  enumeration was measured at ~11.5 GB peak RSS and rejected as a hardware
  bar — is now proved structurally (destructured permutation, closed
  bit-scatter form, carry bounds + omega on the concretized branches
  forward; explicit single-bit counterexamples reverse). Statements are
  unchanged from the native_decide revision, verbatim. Sequence-level
  theorems are structural proofs over EVERY valid ordering, in the style of
  alternations_15_general / switches_30_general.

  ────────────────────────────────────────────────────────────────────────────
  THEOREM STATUS + NOVELTY LEDGER (per the project's attribution rules;
  corrections invited on every "we have not located..." hedge):

  · §TG-1 (trigram factorization layer) — CLASSICAL CONTENT, FORMALIZED.
    That inverting a hexagram swaps and 3-bit-reverses its trigrams, and that
    complementing acts componentwise, are visually obvious classical facts;
    Goldenberg 1975 (J. Chinese Philosophy 2:2, Theorem 4 and the (654321)
    line-permutation framing) is the ambient algebraic prior art, with
    Schöter 1998 for the Boolean-algebra vocabulary. The placement of the 8
    doubled-trigram ("pure") hexagrams in adjacent pairs is a classical
    observation (Lai Zhide, 16th c., via Schulz 1982; Wu Deng's warp/weft
    skeleton, 13th c., via Nielsen 2003). NOTHING here is claimed as a
    discovery; the contribution is the kernel-checked lemma layer only.

  · §TG-2 (forced transition-budget at the trigram level) — PROJECT
    DERIVATION; OBSERVATION CREDITED. The "9th six" observation — every
    canonical King Wen-type sequence has exactly one between-pair transition
    of Hamming distance 6, i.e. one boundary complementing BOTH trigrams
    simultaneously — is due to McKenna & McKenna 1975 (see MCKENNA.md and
    TR-1 row 9; measured universal at 11.2T and 560T). The theorem here
    derives the full forced boundary-distance multiset {1:2, 2:8, 3:13, 4:7,
    6:1} from C1+C5 for EVERY valid ordering, making the measurement a
    corollary. The pangtong-successor and flanking-exclusion corollaries
    appear to be new AS EXPLICIT PROPOSITIONS (hedge: the pangtong relation
    across King Wen's #37-38 → #39-40 boundary may well be remarked in the
    classical or structuralist literature — Schulz's and Cook's pair-relation
    tables are the places to check before any publication claim; corrections
    invited). No first-discovery claim on any component.

  · §TG-3 (trigram-compatible symmetry subgroup) — PROJECT-SPECIFIC.
    ⚠ SCOPE DISTINCTION, stated once here and again at the section head:
    TG-3 is about the order-48 CONSTRAINT-SYMMETRY group G of TR-5 /
    Automorphism.lean — bit-position permutations of the six LINE POSITIONS
    centralizing bit-reversal, acting on orderings. It is NOT about the
    group of operations on the hexagram SET generated by complement,
    reversal, and trigram swap: that group, and its 14-orbit ("families of
    derivation") decomposition of the 64 hexagrams, is Hershock 1991
    (J. Chinese Philosophy 18:3) — a DIFFERENT group acting on a DIFFERENT
    object, machine-verified separately by this project. Any statement about
    the 14-family decomposition, or about his circular reordering built from
    complement, reversal, trigram swap and the nuclear ("linking") map, must
    cite Hershock. Trigram OPERATIONS on hexagrams as such are older and are
    NOT his: ⟨comp, rev⟩ and ⟨rev, swap⟩ are Wu Cheng's (13th c.) and
    ⟨comp, swap⟩ Jiao Xun's (18th c.) — verify.py --check-classical-groups —
    and the two groups are related by more than vocabulary: they share the
    order-4 subgroup ⟨rev, swap⟩, every element of which is a line-position
    permutation in G₁₂; complement is not a line permutation, and that is
    what puts Hershock's group outside the S₆ framing (corrected 2026-09-02;
    Codex V2-F54 #6). TG-3's result
    — exactly 12 of the 48 line-position symmetries respect the trigram
    bipartition, ≅ S₃ × C₂, collapsing to S₃ (order 6) at record level —
    has no located external prior art (the constraint system itself is
    project-specific); Goldenberg 1975 is credited for the ambient
    S₆-on-the-set framing. Corrections invited.

  · §TG-4 (nuclear naturality) — PRESUMABLY CLASSICAL/IMPLICIT; SAY SO.
    The 64 → 16 → 4 nuclear image chain and its terminal set are classical
    (commentary tradition; treated in Hershock 1991 as "linking" and in
    Cook 2006, the source of the nuclear_adj battery). The commutation of
    the nuclear map with reversal/complement and the C1-pairing descent are
    the kind of fact that is visually obvious and very likely stated or
    assumed somewhere in the structuralist literature; we have NOT located
    an explicit statement and claim no discovery — this section certifies
    the well-definedness substrate under the shipped vdb_nuc (V-8) and
    nuclear_adj batteries. Corrections invited.

  · §TG-5 (vacuity guards) — GUARDS, NOT RESULTS; NO NOVELTY CLAIMED.
    Whole-sequence trigram balance is a property of the SET of 64 hexagrams
    (invariant under EVERY permutation), so any "the King Wen sequence
    balances the eight trigrams" claim is vacuous; and pure-hexagram
    adjacency is forced by C1, not a design choice. These are kernel-checked
    precisely because they remove numerology attack surface.
  ────────────────────────────────────────────────────────────────────────────

  Structure:
    §0  definitions restated verbatim from KingWen.lean / Automorphism.lean,
        plus the trigram layer (upperT, lowerT, rev3, d3, nuc, ...)
    §1  TG-1 finite lemmas (decide)
    §2  counting machinery (self-as-range-map bridge, even/odd slot split,
        two-members countP bound) — shared by §3-§5
    §3  TG-2: within-pair multiset, THE BOUNDARY-BUDGET THEOREM (lead),
        9th-six uniqueness in trigram form, single-line-carry corollary,
        C2's trigram reading, pangtong successor, flanking exclusion
    §4  TG-3: G12 (order 12), structure ≅ S₃ × C₂, record-level S₃ (order 6),
        blockwise-action characterization, S₃-invariance of the trigram
        change-count functionals, and the G24-orbit NON-invariance witness
    §5  TG-4 nuclear naturality; TG-5 vacuity guards

  Cross-refs: documentation/TRIGRAM_STRUCTURE.md (prose companion, scope +
  attribution), SPECIFICATION.md (constraints), SYMMETRY_SEARCH.md +
  Automorphism.lean (TR-5 group), MCKENNA.md (9th six), CITATIONS.md
  (credit lines).
  Attribution: developed with AI assistance (Claude, Anthropic).
-/

namespace Trigram

/- ────────── §0a defs restated verbatim from KingWen.lean ────────── -/

/-- popcount for 6-bit values (total, no recursion needed). -/
def pc6 (n : Nat) : Nat :=
  n % 2 + n / 2 % 2 + n / 4 % 2 + n / 8 % 2 + n / 16 % 2 + n / 32 % 2

/-- 6-bit reversal. -/
def rev6 (n : Nat) : Nat :=
  n % 2 * 32 + n / 2 % 2 * 16 + n / 4 % 2 * 8 + n / 8 % 2 * 4 + n / 16 % 2 * 2 + n / 32 % 2

/-- canonical partner: reversal, or complement for palindromes. -/
def partner (h : Nat) : Nat := if rev6 h = h then h ^^^ 63 else rev6 h

/-- Hamming distance on 6-bit values. -/
def ham (a b : Nat) : Nat := pc6 (a ^^^ b)

def KW : List Nat :=
  [63,  0, 17, 34, 23, 58,  2, 16, 55, 59,  7, 56, 61, 47,  4,  8,
   25, 38,  3, 48, 41, 37, 32,  1, 57, 39, 33, 30, 18, 45, 28, 14,
   60, 15, 40,  5, 53, 43, 20, 10, 35, 49, 31, 62, 24,  6, 26, 22,
   29, 46,  9, 36, 52, 11, 13, 44, 54, 27, 50, 19, 51, 12, 21, 42]

/-- adjacent-transition distances of a sequence. -/
def transitions (l : List Nat) : List Nat :=
  (l.zip l.tail).map (fun p => ham p.1 p.2)

/-- C1: consecutive pairing by partner. -/
def c1ok (l : List Nat) : Bool :=
  ((List.range 32).all fun i => l.getD (2*i+1) 99 == partner (l.getD (2*i) 99))

/-- C4. -/
def c4ok (l : List Nat) : Bool := l.getD 0 99 == 63 && l.getD 1 99 == 0

/-- C5: the difference-wave multiset {1:2, 2:20, 3:13, 4:19, 6:9} (implies C2). -/
def c5ok (l : List Nat) : Bool :=
  let t := transitions l
  ((t.filter (· == 1)).length == 2) && ((t.filter (· == 2)).length == 20) &&
  ((t.filter (· == 3)).length == 13) && ((t.filter (· == 4)).length == 19) &&
  ((t.filter (· == 5)).length == 0)  && ((t.filter (· == 6)).length == 9) &&
  ((t.filter (· == 0)).length == 0)

/-- C2 (no distance-5 transition), standalone (restated from Automorphism.lean). -/
def c2ok (l : List Nat) : Bool := ((transitions l).filter (· == 5)).length == 0

/-- x64 complement-distance sum: Σ_h |pos(h) − pos(comp h)|. -/
def c3x64 (l : List Nat) : Nat :=
  ((List.range 64).map fun h =>
    let a := l.findIdx (· == h); let b := l.findIdx (· == (h ^^^ 63))
    max a b - min a b).foldl (·+·) 0

def c3ok (l : List Nat) : Bool := c3x64 l ≤ 776

def validC15 (l : List Nat) : Bool := c1ok l && c4ok l && c5ok l && c3ok l

/-- all permutations of a list (insertion-based; 720 elements for 6 positions). -/
def inserts (x : Nat) : List Nat → List (List Nat)
  | [] => [[x]]
  | y :: ys => (x :: y :: ys) :: (inserts x ys).map (y :: ·)

def perms : List Nat → List (List Nat)
  | [] => [[]]
  | x :: xs => (perms xs).flatMap (inserts x)

/-- apply a bit-position permutation p (bit i of n goes to position p[i]). -/
def applyPerm (p : List Nat) (n : Nat) : Nat :=
  ((List.range 6).map fun i => n / (2^i) % 2 * 2^(p.getD i 0)).foldl (·+·) 0

/-- boundary-transition value at flat index j (restated from KingWen.lean). -/
def ftr (l : List Nat) (j : Nat) : Nat := ham (l.getD j 0) (l.getD (j+1) 0)

/- ────────── §0b defs restated verbatim from Automorphism.lean ────────── -/

/-- the identity bit permutation. -/
def idp : List Nat := [0, 1, 2, 3, 4, 5]

/-- the bit-reversal permutation: applyPerm rho = rev6. -/
def rho : List Nat := [5, 4, 3, 2, 1, 0]

/-- G48 = the centralizer of bit-reversal among the 720 bit permutations
    (order 48, ≅ B₃ ≅ Z₂ ≀ S₃ — the constraint symmetry group of
    SYMMETRY_SEARCH.md / TR-5 / Automorphism.lean). -/
def G48 : List (List Nat) :=
  (perms idp).filter fun p =>
    (List.range 64).all fun h => applyPerm p (rev6 h) == rev6 (applyPerm p h)

/-- record-level coset representatives (order 24): G48 / {id, rho}. -/
def G24 : List (List Nat) := G48.filter fun p => p.getD 0 0 < p.getD 5 0

/-- composition of bit permutations: applyPerm (pcomp p q) = applyPerm p ∘ applyPerm q. -/
def pcomp (p q : List Nat) : List Nat := q.map fun j => p.getD j 0

/- ────────── §0c the trigram layer (new definitions) ────────── -/

/-- popcount for 3-bit values. -/
def pc3 (t : Nat) : Nat := t % 2 + t / 2 % 2 + t / 4 % 2

/-- 3-bit reversal. -/
def rev3 (t : Nat) : Nat := t % 2 * 4 + t / 2 % 2 * 2 + t / 4 % 2

/-- upper trigram: lines 4-6 = bits 3-5 (bit 0 = bottom line, project-wide). -/
def upperT (h : Nat) : Nat := h / 8 % 8

/-- lower trigram: lines 1-3 = bits 0-2. -/
def lowerT (h : Nat) : Nat := h % 8

/-- Hamming distance on 3-bit values (trigram distance). -/
def d3 (a b : Nat) : Nat := pc3 (a ^^^ b)

/-- nuclear hexagram: lower nuclear = lines 2-4, upper nuclear = lines 3-5. -/
def nuc (h : Nat) : Nat := (h / 4 % 8) * 8 + (h / 2 % 8)

/-- pure (doubled-trigram) hexagram: upper trigram = lower trigram. -/
def pureHex (h : Nat) : Bool := upperT h == lowerT h

/-- upper-trigram change count of a sequence (63 adjacent transitions for a
    64-list) — the trigram-locality functional of the E3/R7 scoreboard rider. -/
def uChange (l : List Nat) : Nat :=
  (l.zip l.tail).countP fun q => upperT q.1 != upperT q.2

/-- lower-trigram change count. -/
def lChange (l : List Nat) : Nat :=
  (l.zip l.tail).countP fun q => lowerT q.1 != lowerT q.2

/- ────────── §1 TG-1: the trigram factorization lemma layer ──────────
   CLASSICAL CONTENT (see header ledger): Goldenberg 1975 ambient; pure-pair
   placement is Lai Zhide / Wu Deng (via Schulz 1982 / Nielsen 2003).
   All facts finite, kernel-checked over the 64 hexagrams. -/

/-- TG-1.1: inversion swaps upper↔lower and 3-bit-reverses each component.
    (Goldenberg 1975's (654321) line permutation, read at the trigram level.) -/
theorem rev6_trigram_factor :
    ∀ h, h < 64 → upperT (rev6 h) = rev3 (lowerT h) ∧ lowerT (rev6 h) = rev3 (upperT h) := by
  decide

/-- TG-1.1 (assembled form): rev6 h = rev3(L h)·8 + rev3(U h). -/
theorem rev6_trigram_factor' :
    ∀ h, h < 64 → rev6 h = rev3 (lowerT h) * 8 + rev3 (upperT h) := by
  decide

/-- TG-1.2: complement acts componentwise on the two trigrams, in place. -/
theorem comp6_trigram_componentwise :
    ∀ h, h < 64 → upperT (h ^^^ 63) = upperT h ^^^ 7 ∧ lowerT (h ^^^ 63) = lowerT h ^^^ 7 := by
  decide

/-- TG-1.3: Hamming distance splits over the trigram bipartition. -/
theorem ham_trigram_split :
    ∀ a, a < 64 → ∀ b, b < 64 →
      ham a b = d3 (upperT a) (upperT b) + d3 (lowerT a) (lowerT b) := by
  decide

/-- TG-1.4: a hexagram is symmetric (rev6-fixed) iff its upper trigram is the
    3-bit reversal of its lower trigram. -/
theorem symmetric_iff_trigram :
    ∀ h, h < 64 → ((rev6 h = h) ↔ upperT h = rev3 (lowerT h)) := by
  decide

/-- TG-1.4: exactly 8 symmetric hexagrams. -/
theorem symmetric_count_8 :
    ((List.range 64).filter fun h => rev6 h == h).length = 8 := by
  decide

/-- TG-1.4: exactly 8 anti-symmetric hexagrams (rev6 h = comp6 h; registry R3). -/
theorem antisymmetric_count_8 :
    ((List.range 64).filter fun h => rev6 h == h ^^^ 63).length = 8 := by
  decide

/-- TG-1.4: the symmetric and anti-symmetric classes are disjoint. -/
theorem sym_antisym_disjoint :
    ∀ h, h < 64 → ¬(rev6 h = h ∧ rev6 h = h ^^^ 63) := by
  decide

/-- TG-1.5: the doubled-trigram ("pure") hexagrams are exactly {9t : t < 8}. -/
theorem pure_hexagrams_explicit :
    (List.range 64).filter pureHex = [0, 9, 18, 27, 36, 45, 54, 63] := by
  decide

/-- TG-1.5: the pure class is closed under the canonical partner map. -/
theorem pure_closed_partner :
    ∀ h, h < 64 → pureHex h = true → pureHex (partner h) = true := by
  decide

/-- TG-1.5: the 4 canonical pure pairs — {Qian,Kun}, {Zhen²,Gen²}, {Kan²,Li²},
    {Xun²,Dui²} = {63,0}, {9,36}, {18,45}, {27,54}. (Classical placement
    observation: Lai Zhide via Schulz 1982; Wu Deng via Nielsen 2003.) -/
theorem pure_pairs_explicit :
    partner 0 = 63 ∧ partner 9 = 36 ∧ partner 18 = 45 ∧ partner 27 = 54 := by
  decide

/- ────────── §2 counting machinery (shared by §3-§5) ──────────
   The same machinery class as alternations_15_general: a list-as-range-map
   bridge plus even/odd index-parity splitting of countP. -/

/-- a list is the range-map of its own getD (the self-indexing bridge). -/
theorem self_eq_rangeMap (l : List Nat) :
    l = (List.range l.length).map (fun j => l.getD j 0) := by
  induction l with
  | nil => rfl
  | cons a t ih =>
    rw [List.length_cons, List.range_succ_eq_map, List.map_cons, List.map_map]
    -- head `(fun j => (a::t).getD j 0) 0 = a` closes by rfl; the tail goal is
    -- definitionally ih's statement ((a::t).getD (j+1) 0 = t.getD j 0 reduces
    -- structurally), so congr 1 discharges both (rfl + assumption)
    congr 1

theorem range64_perm :
    (List.range 64).Perm
      (((List.range 32).map (fun i => 2*i)) ++ ((List.range 32).map (fun i => 2*i+1))) := by
  decide

theorem range63_perm :
    (List.range 63).Perm
      (((List.range 32).map (fun i => 2*i)) ++ ((List.range 31).map (fun i => 2*i+1))) := by
  decide

/-- transitions as a range-map (restated from KingWen.lean). -/
theorem transitions_eq_rangeMap (l : List Nat) :
    transitions l = (List.range (l.length - 1)).map
      (fun j => ham (l.getD j 0) (l.getD (j+1) 0)) := by
  induction l with
  | nil => rfl
  | cons a t ih =>
    cases t with
    | nil => rfl
    | cons b t2 =>
      show ham a b :: transitions (b :: t2) = _
      rw [ih]
      have h1 : (a :: b :: t2).length - 1 = ((b :: t2).length - 1) + 1 := by simp
      rw [h1, List.range_succ_eq_map, List.map_cons, List.map_map]
      simp [Function.comp]

/-- splitting a countP over a 64-list into even-slot and odd-slot counts. -/
theorem countP_even_odd_split (l : List Nat) (hlen : l.length = 64) (p : Nat → Bool) :
    l.countP p =
      ((List.range 32).countP fun i => p (l.getD (2*i) 0)) +
      ((List.range 32).countP fun i => p (l.getD (2*i+1) 0)) := by
  conv => lhs; rw [self_eq_rangeMap l, hlen]
  rw [List.countP_map, range64_perm.countP_eq, List.countP_append,
      List.countP_map, List.countP_map]
  rfl

/-- splitting a countP over the 63 transitions into 32 within-pair (even flat
    index) and 31 between-pair (odd flat index) counts. -/
theorem transitions_countP_split (l : List Nat) (hlen : l.length = 64) (p : Nat → Bool) :
    (transitions l).countP p =
      ((List.range 32).countP fun i => p (ftr l (2*i))) +
      ((List.range 31).countP fun i => p (ftr l (2*i+1))) := by
  have htrans : transitions l = (List.range 63).map (ftr l) := by
    rw [transitions_eq_rangeMap, hlen]; rfl
  rw [htrans, List.countP_map, range63_perm.countP_eq, List.countP_append,
      List.countP_map, List.countP_map]
  rfl

/-- one satisfying member bounds countP below by 1. -/
theorem countP_pos_of_mem {α : Type} {l : List α} {p : α → Bool} {a : α}
    (ha : a ∈ l) (hpa : p a = true) : 1 ≤ l.countP p := by
  induction l with
  | nil => cases ha
  | cons c t ih =>
    by_cases hc : p c = true
    · rw [List.countP_cons_of_pos hc]  -- 4.31.0: hypothesis is the only explicit arg
      omega
    · rw [List.countP_cons_of_neg hc]
      cases List.mem_cons.mp ha with
      | inl h => exact absurd (h ▸ hpa) hc
      | inr h => exact ih h

/-- two distinct satisfying members bound countP below by 2 — the engine of
    the flanking-exclusion duplicate argument. -/
theorem countP_ge_two {α : Type} {l : List α} {p : α → Bool} {a b : α}
    (hab : a ≠ b) (ha : a ∈ l) (hb : b ∈ l)
    (hpa : p a = true) (hpb : p b = true) : 2 ≤ l.countP p := by
  induction l with
  | nil => cases ha
  | cons c t ih =>
    cases List.mem_cons.mp ha with
    | inl hac =>
      have hbt : b ∈ t := by
        cases List.mem_cons.mp hb with
        | inl hbc => exact absurd (hac.trans hbc.symm) hab
        | inr h => exact h
      rw [List.countP_cons_of_pos (hac ▸ hpa)]
      have := countP_pos_of_mem hbt hpb
      omega
    | inr hat =>
      cases List.mem_cons.mp hb with
      | inl hbc =>
        rw [List.countP_cons_of_pos (hbc ▸ hpb)]
        have := countP_pos_of_mem hat hpa
        omega
      | inr hbt =>
        have h2 := ih hat hbt
        by_cases hc : p c = true
        · rw [List.countP_cons_of_pos hc]; omega
        · rw [List.countP_cons_of_neg hc]; omega

/-- bounds and length from the permutation hypothesis (restated from
    Automorphism.lean). -/
theorem perm_lt64 {l : List Nat} (hp : l.Perm (List.range 64)) : ∀ x ∈ l, x < 64 :=
  fun _ hx => List.mem_range.mp (hp.mem_iff.mp hx)

theorem perm_len64 {l : List Nat} (hp : l.Perm (List.range 64)) : l.length = 64 := by
  simpa using hp.length_eq

/-- getD bound helper (the hget pattern of KingWen.lean). -/
theorem getD_lt64 {l : List Nat} (hb : ∀ x ∈ l, x < 64) (hlen : l.length = 64) :
    ∀ j, j < 64 → l.getD j 0 < 64 := by
  intro j hj
  have hjl : j < l.length := by omega
  have : l.getD j 0 = l[j] := by simp [List.getD, List.getElem?_eq_getElem hjl]
  rw [this]; exact hb _ (List.getElem_mem hjl)

/-- C1 accessor in getD-0 form (the hc1 pattern of KingWen.lean). -/
theorem c1_getD {l : List Nat} (hlen : l.length = 64) (h1 : c1ok l = true) :
    ∀ i, i < 32 → l.getD (2*i+1) 0 = partner (l.getD (2*i) 0) := by
  intro i hi
  simp only [c1ok, List.all_eq_true, beq_iff_eq] at h1
  have h2i : 2*i < l.length := by omega
  have h2i1 : 2*i+1 < l.length := by omega
  have e1 : l.getD (2*i+1) 99 = l.getD (2*i+1) 0 := by
    simp [List.getD, List.getElem?_eq_getElem h2i1]
  have e2 : l.getD (2*i) 99 = l.getD (2*i) 0 := by
    simp [List.getD, List.getElem?_eq_getElem h2i]
  have := h1 i (List.mem_range.mpr hi)
  rw [e1, e2] at this; exact this

/-- each value below 64 occurs exactly once in range 64 — the uniqueness
    engine behind the flanking exclusion. -/
theorem range64_count_unique :
    ∀ v, v < 64 → ((List.range 64).countP fun x => x == v) = 1 := by
  decide

/-- doubling engine: for any pair-class-invariant predicate p, the even-slot
    count over a C1-valid ordering doubles to the full range-64 count.
    (Each partner-pair contributes its two members, one to each slot parity.) -/
theorem within_double (l : List Nat) (hperm : l.Perm (List.range 64))
    (h1 : c1ok l = true) (p : Nat → Bool) (hp : ∀ h, h < 64 → p (partner h) = p h) :
    2 * ((List.range 32).countP fun i => p (l.getD (2*i) 0)) =
      (List.range 64).countP p := by
  have hb := perm_lt64 hperm
  have hlen := perm_len64 hperm
  have hget := getD_lt64 hb hlen
  have hc1 := c1_getD hlen h1
  have hsplit := countP_even_odd_split l hlen p
  have hodd : ((List.range 32).countP fun i => p (l.getD (2*i+1) 0)) =
      ((List.range 32).countP fun i => p (l.getD (2*i) 0)) := by
    apply List.countP_congr
    intro i hi
    have hi32 := List.mem_range.mp hi
    rw [hc1 i hi32, hp _ (hget (2*i) (by omega))]
  have hcount : l.countP p = (List.range 64).countP p := hperm.countP_eq p
  -- confirmed 4.31.0: `hperm.countP_eq p` (explicit predicate) elaborates as written
  omega

/- ────────── §3 TG-2: the forced transition budget, read at the trigram level ──────────
   ★ lead theorem family. Observation credit: McKenna & McKenna 1975 (the
   "9th six"); the derivation + kernel check are the project's contribution.
   Machinery: the same class as alternations_15_general (range-map bridge +
   index-parity multiset counting). -/

/- --- §3a finite facts (decide over 64 / 64×64) --- -/

/-- within-pair distances take only the values 2, 4, 6, with population counts
    48 = 24+24 over hexagrams, i.e. multiset {2:12, 4:12, 6:8} over the 32
    pairs (each pair counted twice below, once per member). -/
theorem pairdist_count_0 : ((List.range 64).countP fun h => ham h (partner h) == 0) = 0 := by
  decide
theorem pairdist_count_1 : ((List.range 64).countP fun h => ham h (partner h) == 1) = 0 := by
  decide
theorem pairdist_count_2 : ((List.range 64).countP fun h => ham h (partner h) == 2) = 24 := by
  decide
theorem pairdist_count_3 : ((List.range 64).countP fun h => ham h (partner h) == 3) = 0 := by
  decide
theorem pairdist_count_4 : ((List.range 64).countP fun h => ham h (partner h) == 4) = 24 := by
  decide
theorem pairdist_count_5 : ((List.range 64).countP fun h => ham h (partner h) == 5) = 0 := by
  decide
theorem pairdist_count_6 : ((List.range 64).countP fun h => ham h (partner h) == 6) = 16 := by
  decide

/-- the within-pair distance is invariant under swapping the pair's orientation
    (ham is symmetric; partner is an involution). -/
theorem pairdist_partner_inv :
    ∀ h, h < 64 → ham (partner h) (partner (partner h)) = ham h (partner h) := by
  decide

/-- distance 6 means full complement. -/
theorem ham_six_comp : ∀ a, a < 64 → ∀ b, b < 64 → ham a b = 6 → b = a ^^^ 63 := by
  decide

/-- trigram reading of distance 6: BOTH trigrams simultaneously complemented
    (both trigram distances equal 3) — McKenna's "9th six" condition. -/
theorem ham_six_trigram_bool :
    ∀ a, a < 64 → ∀ b, b < 64 →
      ((ham a b == 6) =
       (d3 (upperT a) (upperT b) == 3 && d3 (lowerT a) (lowerT b) == 3)) := by
  decide

/-- trigram reading of distance 5 — the C2 content: d = 5 iff one trigram is
    fully complemented (distance 3) while the other changes exactly 2 lines. -/
theorem ham_five_trigram_bool :
    ∀ a, a < 64 → ∀ b, b < 64 →
      ((ham a b == 5) =
       ((d3 (upperT a) (upperT b) == 3 && d3 (lowerT a) (lowerT b) == 2) ||
        (d3 (upperT a) (upperT b) == 2 && d3 (lowerT a) (lowerT b) == 3))) := by
  decide

/-- trigram reading of distance 1: exactly one line changes, i.e. one whole
    trigram is carried over intact while the other moves one line. -/
theorem ham_one_trigram_bool :
    ∀ a, a < 64 → ∀ b, b < 64 →
      ((ham a b == 1) =
       ((upperT a == upperT b && d3 (lowerT a) (lowerT b) == 1) ||
        (lowerT a == lowerT b && d3 (upperT a) (upperT b) == 1))) := by
  decide

/-- the pangtong engine: chasing complement through the partner involution.
    (partner∘comp∘partner = comp on all 64 hexagrams.) -/
theorem partner_comp_partner :
    ∀ h, h < 64 → partner (partner h ^^^ 63) = h ^^^ 63 := by
  decide

/-- complement is an involution on 6-bit values. -/
theorem comp_comp : ∀ h, h < 64 → (h ^^^ 63) ^^^ 63 = h := by
  decide

/-- a pair is self-complementary ({h, partner h} = {h, comp h}) iff its
    members are symmetric or anti-symmetric; exactly 16 such hexagrams
    (= the 4 symmetric pairs + the 4 anti-symmetric pairs). -/
theorem selfcomp_pair_iff :
    ∀ h, h < 64 → ((partner h = h ^^^ 63) ↔ (rev6 h = h ∨ rev6 h = h ^^^ 63)) := by
  decide

theorem selfcomp_pair_count :
    ((List.range 64).countP fun h => partner h == h ^^^ 63) = 16 := by
  decide

/- --- §3b the within-pair multiset (TG-2 prop 1, previously prose-only) --- -/

/-- THE WITHIN-PAIR MULTISET THEOREM: in EVERY C1-valid ordering of the 64
    hexagrams, the 32 within-pair transition distances form the multiset
    {2:12, 4:12, 6:8} — fixed by the partner involution alone (C1 fixes the
    pair SET, so the multiset cannot vary across the solution space).
    This is CITATIONS.md's 2×12 + 4×12 + 6×8 = 120 table, machine-checked. -/
theorem within_multiset_general (l : List Nat) (hperm : l.Perm (List.range 64))
    (h1 : c1ok l = true) :
    ((List.range 32).countP fun i => ftr l (2*i) == 0) = 0 ∧
    ((List.range 32).countP fun i => ftr l (2*i) == 1) = 0 ∧
    ((List.range 32).countP fun i => ftr l (2*i) == 2) = 12 ∧
    ((List.range 32).countP fun i => ftr l (2*i) == 3) = 0 ∧
    ((List.range 32).countP fun i => ftr l (2*i) == 4) = 12 ∧
    ((List.range 32).countP fun i => ftr l (2*i) == 5) = 0 ∧
    ((List.range 32).countP fun i => ftr l (2*i) == 6) = 8 := by
  have hb := perm_lt64 hperm
  have hlen := perm_len64 hperm
  have hget := getD_lt64 hb hlen
  have hc1 := c1_getD hlen h1
  -- bridge each within-transition count to a pair-class predicate count
  have hbridge : ∀ v, ((List.range 32).countP fun i => ftr l (2*i) == v) =
      ((List.range 32).countP fun i =>
        ham (l.getD (2*i) 0) (partner (l.getD (2*i) 0)) == v) := by
    intro v
    apply List.countP_congr
    intro i hi
    have hi32 := List.mem_range.mp hi
    -- 4.31.0: countP_congr wants an iff, so rewrite the ftr value and close by rfl
    have hftr : ftr l (2*i) = ham (l.getD (2*i) 0) (partner (l.getD (2*i) 0)) := by
      unfold ftr; rw [hc1 i hi32]
    rw [hftr]
  -- doubling: even-slot pair-class count doubles to the range-64 count
  have hcore : ∀ v, 2 * ((List.range 32).countP fun i =>
      ham (l.getD (2*i) 0) (partner (l.getD (2*i) 0)) == v) =
      ((List.range 64).countP fun h => ham h (partner h) == v) := by
    intro v
    exact within_double l hperm h1 (fun h => ham h (partner h) == v)
      (fun h hh => by rw [pairdist_partner_inv h hh])
    -- confirmed 4.31.0: `exact` unifies the beta-reduced statement form as written
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · have hb0 := hbridge 0; have hc0 := hcore 0; have hd0 := pairdist_count_0; omega
  · have hb1 := hbridge 1; have hc1' := hcore 1; have hd1 := pairdist_count_1; omega
  · have hb2 := hbridge 2; have hc2 := hcore 2; have hd2 := pairdist_count_2; omega
  · have hb3 := hbridge 3; have hc3 := hcore 3; have hd3 := pairdist_count_3; omega
  · have hb4 := hbridge 4; have hc4 := hcore 4; have hd4 := pairdist_count_4; omega
  · have hb5 := hbridge 5; have hc5 := hcore 5; have hd5 := pairdist_count_5; omega
  · have hb6 := hbridge 6; have hc6 := hcore 6; have hd6 := pairdist_count_6; omega

/- --- §3c THE BOUNDARY-BUDGET THEOREM (TG-2 prop 2) ★ --- -/

/-- THE FORCED BOUNDARY-DISTANCE MULTISET: in EVERY C1+C5 ordering of the 64
    hexagrams, the 31 between-pair ("boundary") transition distances form
    exactly the multiset {1:2, 2:8, 3:13, 4:7, 6:1} — C5's total transition
    multiset minus the C1-forced within-pair multiset. In particular:
    · EXACTLY ONE boundary has distance 6 — the unique transition that
      complements both trigrams simultaneously (McKenna & McKenna 1975's
      "9th six"; the 11.2T/560T-universal measurement becomes a corollary);
    · EXACTLY TWO boundaries change a single line;
    · no boundary has distance 0 or 5.
    This is the project's fourth sequence-level theorem (after wrap parity,
    15 alternations, 30 switches) and the first with trigram content. -/
theorem boundary_budget_general (l : List Nat) (hperm : l.Perm (List.range 64))
    (h1 : c1ok l = true) (h5 : c5ok l = true) :
    ((List.range 31).countP fun k => ftr l (2*k+1) == 0) = 0 ∧
    ((List.range 31).countP fun k => ftr l (2*k+1) == 1) = 2 ∧
    ((List.range 31).countP fun k => ftr l (2*k+1) == 2) = 8 ∧
    ((List.range 31).countP fun k => ftr l (2*k+1) == 3) = 13 ∧
    ((List.range 31).countP fun k => ftr l (2*k+1) == 4) = 7 ∧
    ((List.range 31).countP fun k => ftr l (2*k+1) == 5) = 0 ∧
    ((List.range 31).countP fun k => ftr l (2*k+1) == 6) = 1 := by
  have hlen := perm_len64 hperm
  have hw := within_multiset_general l hperm h1
  -- pin the split at each value in beta-normal statement form
  have hsplit : ∀ v, (transitions l).countP (fun x => x == v) =
      ((List.range 32).countP fun i => ftr l (2*i) == v) +
      ((List.range 31).countP fun k => ftr l (2*k+1) == v) := by
    intro v
    exact transitions_countP_split l hlen (fun x => x == v)
    -- confirmed 4.31.0: beta-reduced instantiation accepted; no bridge needed
  -- countP ↔ filter-length, to consume c5ok's filter form
  have htot : ∀ v, (transitions l).countP (fun x => x == v) =
      ((transitions l).filter (fun x => x == v)).length := by
    intro v
    exact List.countP_eq_length_filter
    -- 4.31.0: all args implicit (KingWen uses it in rw form
    -- `← List.countP_eq_length_filter`)
  simp only [c5ok, Bool.and_eq_true, beq_iff_eq] at h5
  -- h5 components (left-assoc &&): .1.1.1.1.1.1 = (=1)→2, .1.1.1.1.1.2 = (=2)→20,
  -- .1.1.1.1.2 = (=3)→13, .1.1.1.2 = (=4)→19, .1.1.2 = (=5)→0, .1.2 = (=6)→9,
  -- .2 = (=0)→0
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · have hs := hsplit 0; rw [htot 0] at hs
    have h50 := h5.2; have := hw.1; omega
  · have hs := hsplit 1; rw [htot 1] at hs
    have h51 := h5.1.1.1.1.1.1; have := hw.2.1; omega
  · have hs := hsplit 2; rw [htot 2] at hs
    have h52 := h5.1.1.1.1.1.2; have := hw.2.2.1; omega
  · have hs := hsplit 3; rw [htot 3] at hs
    have h53 := h5.1.1.1.1.2; have := hw.2.2.2.1; omega
  · have hs := hsplit 4; rw [htot 4] at hs
    have h54 := h5.1.1.1.2; have := hw.2.2.2.2.1; omega
  · have hs := hsplit 5; rw [htot 5] at hs
    have h55 := h5.1.1.2; have := hw.2.2.2.2.2.1; omega
  · have hs := hsplit 6; rw [htot 6] at hs
    have h56 := h5.1.2; have := hw.2.2.2.2.2.2; omega

/- --- §3d trigram-form corollaries of the budget --- -/

/-- THE 9TH SIX, IN TRIGRAM FORM (McKenna & McKenna 1975, derived): every
    C1+C5 ordering has EXACTLY ONE boundary at which both trigrams are
    simultaneously complemented (both trigram distances = 3). -/
theorem ninth_six_trigram (l : List Nat) (hperm : l.Perm (List.range 64))
    (h1 : c1ok l = true) (h5 : c5ok l = true) :
    ((List.range 31).countP fun k =>
      d3 (upperT (l.getD (2*k+1) 0)) (upperT (l.getD (2*k+2) 0)) == 3 &&
      d3 (lowerT (l.getD (2*k+1) 0)) (lowerT (l.getD (2*k+2) 0)) == 3) = 1 := by
  have hb := perm_lt64 hperm
  have hlen := perm_len64 hperm
  have hget := getD_lt64 hb hlen
  have h6 := (boundary_budget_general l hperm h1 h5).2.2.2.2.2.2
  have hcongr : ((List.range 31).countP fun k =>
      d3 (upperT (l.getD (2*k+1) 0)) (upperT (l.getD (2*k+2) 0)) == 3 &&
      d3 (lowerT (l.getD (2*k+1) 0)) (lowerT (l.getD (2*k+2) 0)) == 3) =
      ((List.range 31).countP fun k => ftr l (2*k+1) == 6) := by
    apply List.countP_congr
    intro k hk
    have hk31 := List.mem_range.mp hk
    have e22 : 2*k+1+1 = 2*k+2 := by omega
    have ha := hget (2*k+1) (by omega)
    have hb2 := hget (2*k+2) (by omega)
    have hftr : ftr l (2*k+1) = ham (l.getD (2*k+1) 0) (l.getD (2*k+2) 0) := by
      unfold ftr; rw [e22]
    rw [hftr, ham_six_trigram_bool _ ha _ hb2]
  exact hcongr.trans h6

/-- SINGLE-LINE-CARRY COROLLARY: exactly two boundaries change a single line —
    each such boundary necessarily carries one whole trigram over intact while
    the other moves exactly one line.
    ⚠ Scope note (do not overstate): "carries a trigram intact" is NOT
    exclusive to d=1 boundaries — a d ∈ {2,3} boundary whose trigram split is
    {0,d} also carries a trigram intact, and how many such boundaries exist is
    ordering-dependent (King Wen itself has 9 intact-carry boundaries, only 2
    of them at d=1). Only the d=1 count is forced. -/
theorem single_line_carry (l : List Nat) (hperm : l.Perm (List.range 64))
    (h1 : c1ok l = true) (h5 : c5ok l = true) :
    ((List.range 31).countP fun k =>
      (upperT (l.getD (2*k+1) 0) == upperT (l.getD (2*k+2) 0) &&
       d3 (lowerT (l.getD (2*k+1) 0)) (lowerT (l.getD (2*k+2) 0)) == 1) ||
      (lowerT (l.getD (2*k+1) 0) == lowerT (l.getD (2*k+2) 0) &&
       d3 (upperT (l.getD (2*k+1) 0)) (upperT (l.getD (2*k+2) 0)) == 1)) = 2 := by
  have hb := perm_lt64 hperm
  have hlen := perm_len64 hperm
  have hget := getD_lt64 hb hlen
  have h1c := (boundary_budget_general l hperm h1 h5).2.1
  have hcongr : ((List.range 31).countP fun k =>
      (upperT (l.getD (2*k+1) 0) == upperT (l.getD (2*k+2) 0) &&
       d3 (lowerT (l.getD (2*k+1) 0)) (lowerT (l.getD (2*k+2) 0)) == 1) ||
      (lowerT (l.getD (2*k+1) 0) == lowerT (l.getD (2*k+2) 0) &&
       d3 (upperT (l.getD (2*k+1) 0)) (upperT (l.getD (2*k+2) 0)) == 1)) =
      ((List.range 31).countP fun k => ftr l (2*k+1) == 1) := by
    apply List.countP_congr
    intro k hk
    have hk31 := List.mem_range.mp hk
    have e22 : 2*k+1+1 = 2*k+2 := by omega
    have ha := hget (2*k+1) (by omega)
    have hb2 := hget (2*k+2) (by omega)
    have hftr : ftr l (2*k+1) = ham (l.getD (2*k+1) 0) (l.getD (2*k+2) 0) := by
      unfold ftr; rw [e22]
    rw [hftr, ham_one_trigram_bool _ ha _ hb2]
  exact hcongr.trans h1c

/-- C2's TRIGRAM READING: C2 (no distance-5 transition) says precisely that
    no transition — within-pair or boundary — may complement one trigram
    (all 3 lines) while changing exactly 2 lines of the other. (Complementing
    one trigram is otherwise legal: it occurs inside d ∈ {3,4,6}.) -/
theorem c2_trigram_reading (l : List Nat) (hb : ∀ x ∈ l, x < 64)
    (hlen : l.length = 64) (h2 : c2ok l = true) :
    ((List.range 63).countP fun j =>
      (d3 (upperT (l.getD j 0)) (upperT (l.getD (j+1) 0)) == 3 &&
       d3 (lowerT (l.getD j 0)) (lowerT (l.getD (j+1) 0)) == 2) ||
      (d3 (upperT (l.getD j 0)) (upperT (l.getD (j+1) 0)) == 2 &&
       d3 (lowerT (l.getD j 0)) (lowerT (l.getD (j+1) 0)) == 3)) = 0 := by
  have hget := getD_lt64 hb hlen
  rw [List.countP_eq_zero]
  -- confirmed 4.31.0: countP_eq_zero rewrites as an iff (core, as in R10)
  intro j hj
  have hj63 := List.mem_range.mp hj
  have ha := hget j (by omega)
  have hb2 := hget (j+1) (by omega)
  -- the pattern at j is exactly (ftr l j == 5)
  have hpat : ((d3 (upperT (l.getD j 0)) (upperT (l.getD (j+1) 0)) == 3 &&
       d3 (lowerT (l.getD j 0)) (lowerT (l.getD (j+1) 0)) == 2) ||
      (d3 (upperT (l.getD j 0)) (upperT (l.getD (j+1) 0)) == 2 &&
       d3 (lowerT (l.getD j 0)) (lowerT (l.getD (j+1) 0)) == 3)) =
      (ftr l j == 5) := by
    show _ = (ham (l.getD j 0) (l.getD (j+1) 0) == 5)
    rw [ham_five_trigram_bool _ ha _ hb2]
  rw [hpat]
  -- ftr l j is a member of transitions l, and c2ok forbids the value 5 there
  simp only [c2ok, beq_iff_eq] at h2
  have hmem : ftr l j ∈ transitions l := by
    have htrans : transitions l = (List.range 63).map (ftr l) := by
      rw [transitions_eq_rangeMap, hlen]; rfl
    rw [htrans]
    exact List.mem_map.mpr ⟨j, hj, rfl⟩
  have hz : (transitions l).countP (fun x => x == 5) = 0 := by
    rw [List.countP_eq_length_filter]; exact h2
    -- confirmed 4.31.0: `(· == 5)` and `fun x => x == 5` elaborate identically
  have := List.countP_eq_zero.mp hz _ hmem
  simpa using this

/-- PANGTONG-SUCCESSOR COROLLARY (new-to-project as an explicit proposition;
    hedged — see header ledger): at the unique d=6 boundary, the following
    pair is exactly the complement (pangtong) image of the preceding pair,
    in reversed order:  s[2k+2] = comp s[2k+1]  and  s[2k+3] = comp s[2k].
    (In King Wen: pairs #37-38 → #39-40 across the 38→39 boundary.)
    The unordered form { s[2k+2], s[2k+3] } = { comp s[2k], comp s[2k+1] }
    is an immediate consequence. -/
theorem pangtong_successor (l : List Nat) (hperm : l.Perm (List.range 64))
    (h1 : c1ok l = true) (k : Nat) (hk : k < 31)
    (h6 : ftr l (2*k+1) = 6) :
    l.getD (2*k+2) 0 = l.getD (2*k+1) 0 ^^^ 63 ∧
    l.getD (2*k+3) 0 = l.getD (2*k) 0 ^^^ 63 := by
  have hb := perm_lt64 hperm
  have hlen := perm_len64 hperm
  have hget := getD_lt64 hb hlen
  have hc1 := c1_getD hlen h1
  have e22 : 2*k+1+1 = 2*k+2 := by omega
  have h6' : ham (l.getD (2*k+1) 0) (l.getD (2*k+2) 0) = 6 := by
    unfold ftr at h6
    rw [e22] at h6
    exact h6
  have hcomp : l.getD (2*k+2) 0 = l.getD (2*k+1) 0 ^^^ 63 :=
    ham_six_comp _ (hget (2*k+1) (by omega)) _ (hget (2*k+2) (by omega)) h6'
  refine ⟨hcomp, ?_⟩
  have ha := hc1 k (by omega)
  have hb2 := hc1 (k+1) (by omega)
  have e1 : 2*(k+1) = 2*k+2 := by omega
  have e2 : 2*(k+1)+1 = 2*k+3 := by omega
  rw [e2, e1] at hb2  -- e2 first: rewriting e1 first destroys e2's 2*(k+1)+1 pattern
  rw [hb2, hcomp, ha]
  exact partner_comp_partner _ (hget (2*k) (by omega))

/-- FLANKING-EXCLUSION COROLLARY (new-to-project as an explicit proposition;
    hedged — see header ledger): neither the pair preceding nor the pair
    following the unique d=6 boundary can be a self-complementary pair —
    i.e. neither can be one of the 4 symmetric pairs or the 4 anti-symmetric
    pairs (selfcomp_pair_iff); only the 24 generic pairs can flank the 9th
    six. Reason: a self-complementary flanking pair would force a duplicated
    hexagram, contradicting the permutation property. -/
theorem flanking_exclusion (l : List Nat) (hperm : l.Perm (List.range 64))
    (h1 : c1ok l = true) (k : Nat) (hk : k < 31)
    (h6 : ftr l (2*k+1) = 6) :
    ¬(partner (l.getD (2*k) 0) = l.getD (2*k) 0 ^^^ 63) ∧
    ¬(partner (l.getD (2*k+2) 0) = l.getD (2*k+2) 0 ^^^ 63) := by
  have hb := perm_lt64 hperm
  have hlen := perm_len64 hperm
  have hget := getD_lt64 hb hlen
  have hc1 := c1_getD hlen h1
  have hpang := pangtong_successor l hperm h1 k hk h6
  constructor
  · -- preceding pair: selfcomp would give s[2k+2] = s[2k], a duplicate at
    -- even slots k and k+1
    intro hself
    have ha := hc1 k (by omega)
    have hs2 : l.getD (2*k+2) 0 = l.getD (2*k) 0 := by
      rw [hpang.1, ha, hself]
      exact comp_comp _ (hget (2*k) (by omega))
    have hv := hget (2*k) (by omega)
    have hcount : l.countP (fun x => x == l.getD (2*k) 0) = 1 :=
      (hperm.countP_eq _).trans (range64_count_unique _ hv)
      -- confirmed 4.31.0: Perm.countP_eq explicit-arg shape as written
    have hsplit := countP_even_odd_split l hlen (fun x => x == l.getD (2*k) 0)
    have h2 : 2 ≤ ((List.range 32).countP fun i =>
        l.getD (2*i) 0 == l.getD (2*k) 0) := by  -- beta-normal, matching hsplit's atom
      apply countP_ge_two (a := k) (b := k+1)
      · omega
      · exact List.mem_range.mpr (by omega)
      · exact List.mem_range.mpr (by omega)
      · simp
      · have e1 : 2*(k+1) = 2*k+2 := by omega
        show (l.getD (2*(k+1)) 0 == l.getD (2*k) 0) = true
        rw [e1, hs2]
        simp
    omega
  · -- following pair: selfcomp would give s[2k+3] = s[2k+1], a duplicate at
    -- odd slots k and k+1
    intro hself
    have hb2 := hc1 (k+1) (by omega)
    have e1 : 2*(k+1) = 2*k+2 := by omega
    have e2 : 2*(k+1)+1 = 2*k+3 := by omega
    rw [e2, e1] at hb2  -- e2 first: rewriting e1 first destroys e2's 2*(k+1)+1 pattern
    have hs3 : l.getD (2*k+3) 0 = l.getD (2*k+1) 0 := by
      rw [hb2, hself, hpang.1]
      exact comp_comp _ (hget (2*k+1) (by omega))
    have hv := hget (2*k+1) (by omega)
    have hcount : l.countP (fun x => x == l.getD (2*k+1) 0) = 1 :=
      (hperm.countP_eq _).trans (range64_count_unique _ hv)
    have hsplit := countP_even_odd_split l hlen (fun x => x == l.getD (2*k+1) 0)
    have h2 : 2 ≤ ((List.range 32).countP fun i =>
        l.getD (2*i+1) 0 == l.getD (2*k+1) 0) := by  -- beta-normal, matching hsplit's atom
      apply countP_ge_two (a := k) (b := k+1)
      · omega
      · exact List.mem_range.mpr (by omega)
      · exact List.mem_range.mpr (by omega)
      · simp
      · have e3 : 2*(k+1)+1 = 2*k+3 := by omega
        show (l.getD (2*(k+1)+1) 0 == l.getD (2*k+1) 0) = true
        rw [e3, hs3]
        simp
    omega

/- ────────── §4 TG-3: the trigram-compatible symmetry subgroup ──────────
   ⚠ SCOPE DISTINCTION (restated from the header, deliberately): everything
   in this section concerns the order-48 group G48 of LINE-POSITION
   permutations centralizing bit-reversal — the constraint-symmetry group of
   TR-5 / SYMMETRY_SEARCH.md / Automorphism.lean, acting on orderings. It is
   NOT the group of operations on the hexagram SET generated by complement,
   reversal, and trigram swap; that group and its 14-orbit decomposition of
   the 64 hexagrams belong to Hershock 1991 (J. Chinese Philosophy 18:3) and
   are a different mathematical object. No statement below overlaps
   Hershock's result, and none should be quoted as if it did. -/

/-- σ preserves the trigram bipartition {{lines 1-3}, {lines 4-6}} as an
    UNORDERED block pair: the image of {bit 0, bit 1, bit 2} is either
    {0,1,2} (blocks fixed) or {3,4,5} (blocks swapped). -/
def blockPreserving (p : List Nat) : Bool :=
  ((p.take 3).all fun x => x < 3) || ((p.take 3).all fun x => 3 ≤ x)

/-- G12 = the trigram-compatible subgroup of the constraint symmetry group. -/
def G12 : List (List Nat) := G48.filter blockPreserving

/-- G6 = the record-level (orientation-quotient) representatives of G12,
    following Automorphism.lean's G24 coset-representative convention. -/
def G6 : List (List Nat) := G12.filter fun p => p.getD 0 0 < p.getD 5 0

/-- the six permutations of the three within-block positions. -/
def perms3 : List (List Nat) := perms [0, 1, 2]

/-- embed a 3-position permutation q as the block-fixing element of G48 that
    acts as q on the lower block and as its reversal-mirror on the upper block
    (positions j and 5−j are identified by bit-reversal, so commuting with
    rev6 forces the upper action to be the ρ-conjugate of the lower action):
    mirrorDouble q = q ++ (reverse q).map (5 − ·). -/
def mirrorDouble (q : List Nat) : List Nat :=
  q ++ (q.reverse.map fun x => 5 - x)

/- ------------------ machinery (adapted from PruneGInvariance §0b) ------------------ -/

theorem mem_inserts_perm {x : Nat} : ∀ {l q : List Nat}, q ∈ inserts x l → q.Perm (x :: l)
  | [], q, hq => by
      simp only [inserts, List.mem_cons, List.not_mem_nil, or_false] at hq
      subst hq; exact List.Perm.refl _
  | y :: ys, q, hq => by
      simp only [inserts, List.mem_cons, List.mem_map] at hq
      rcases hq with rfl | ⟨q', hq', rfl⟩
      · exact List.Perm.refl _
      · exact (List.Perm.cons y (mem_inserts_perm hq')).trans (List.Perm.swap x y ys)

theorem mem_perms_perm : ∀ {l q : List Nat}, q ∈ perms l → q.Perm l
  | [], q, hq => by
      simp only [perms, List.mem_cons, List.not_mem_nil, or_false] at hq
      subst hq; exact List.Perm.refl _
  | x :: xs, q, hq => by
      simp only [perms, List.mem_flatMap] at hq
      obtain ⟨r, hr, hq2⟩ := hq
      exact (mem_inserts_perm hq2).trans (List.Perm.cons x (mem_perms_perm hr))

theorem foldl_add_eq_sum : ∀ (l : List Nat) (a : Nat), l.foldl (·+·) a = a + l.sum
  | [], a => by simp
  | x :: xs, a => by
      rw [List.foldl_cons, foldl_add_eq_sum xs (a + x), List.sum_cons]
      omega

def bitsum : List Nat → Nat → Nat
  | [], _ => 0
  | x :: xs, n => n % 2 * 2^x + bitsum xs (n / 2)

theorem range_map_bits (q : List Nat) : ∀ n : Nat,
    ((List.range q.length).map fun i => n / 2^i % 2 * 2^(q.getD i 0)).sum = bitsum q n := by
  induction q with
  | nil => intro n; rfl
  | cons x xs ih =>
      intro n
      rw [List.length_cons, List.range_succ_eq_map, List.map_cons, List.map_map, List.sum_cons]
      have hhead : n / 2^0 % 2 * 2^((x :: xs).getD 0 0) = n % 2 * 2^x := by
        simp
      have htail : ((List.range xs.length).map
          ((fun i => n / 2^i % 2 * 2^((x :: xs).getD i 0)) ∘ Nat.succ)).sum
          = bitsum xs (n / 2) := by
        rw [← ih (n / 2)]
        apply congrArg
        apply List.map_congr_left
        intro i _
        simp only [Function.comp, Nat.succ_eq_add_one, List.getD_cons_succ]
        have hdiv : n / 2 ^ (i + 1) = n / 2 / 2 ^ i := by
          rw [Nat.div_div_eq_div_mul, ← Nat.pow_succ']
        rw [hdiv]
      rw [hhead, htail]
      rfl

theorem applyPerm_eq_bitsum (p : List Nat) (hlen : p.length = 6) (n : Nat) :
    applyPerm p n = bitsum p n := by
  unfold applyPerm
  rw [foldl_add_eq_sum, Nat.zero_add, ← hlen, range_map_bits]

/- ------------------ the closed 6-entry form ------------------ -/

/-- applyPerm on a destructured permutation, in bitsum's exact nesting. -/
theorem applyPerm6 (a0 a1 a2 a3 a4 a5 x : Nat) :
    applyPerm [a0, a1, a2, a3, a4, a5] x =
      x % 2 * 2^a0 + (x/2 % 2 * 2^a1 + (x/2/2 % 2 * 2^a2 +
        (x/2/2/2 % 2 * 2^a3 + (x/2/2/2/2 % 2 * 2^a4 +
          (x/2/2/2/2/2 % 2 * 2^a5 + 0))))) := by
  rw [applyPerm_eq_bitsum _ rfl]
  rfl

/-- ... regrouped into the (lower-block sources) + (upper-block sources) split. -/
theorem applyPerm6_split (a0 a1 a2 a3 a4 a5 x : Nat) :
    applyPerm [a0, a1, a2, a3, a4, a5] x =
      (x % 2 * 2^a0 + x/2 % 2 * 2^a1 + x/4 % 2 * 2^a2) +
      (x/8 % 2 * 2^a3 + x/16 % 2 * 2^a4 + x/32 % 2 * 2^a5) := by
  rw [applyPerm6]
  rw [show x/2/2 = x/4 from by omega]
  rw [show x/4/2 = x/8 from by omega]
  rw [show x/8/2 = x/16 from by omega]
  rw [show x/16/2 = x/32 from by omega]
  simp only [Nat.add_zero, Nat.add_assoc]

/-- three distinct sub-3 scatter positions carry three bits into a value < 8. -/
theorem lowsum_le7 {e0 e1 e2 u v w : Nat} (h0 : e0 < 3) (h1 : e1 < 3) (h2 : e2 < 3)
    (d01 : e0 ≠ e1) (d02 : e0 ≠ e2) (d12 : e1 ≠ e2)
    (hu : u ≤ 1) (hv : v ≤ 1) (hw : w ≤ 1) :
    u * 2^e0 + v * 2^e1 + w * 2^e2 ≤ 7 := by
  have he0 : e0 = 0 ∨ e0 = 1 ∨ e0 = 2 := by omega
  have he1 : e1 = 0 ∨ e1 = 1 ∨ e1 = 2 := by omega
  have he2 : e2 = 0 ∨ e2 = 1 ∨ e2 = 2 := by omega
  rcases he0 with rfl | rfl | rfl <;> rcases he1 with rfl | rfl | rfl <;>
    rcases he2 with rfl | rfl | rfl <;>
    simp only [show (2:Nat)^0 = 1 from rfl, show (2:Nat)^1 = 2 from rfl,
      show (2:Nat)^2 = 4 from rfl] at * <;> omega

/- ------------------ THE THEOREM, original statement ------------------ -/

/-- Boolean unfold of blockPreserving on a destructured list. -/
theorem blockPreserving6 (a0 a1 a2 a3 a4 a5 : Nat) :
    blockPreserving [a0, a1, a2, a3, a4, a5] = true ↔
      ((a0 < 3 ∧ a1 < 3 ∧ a2 < 3) ∨ (3 ≤ a0 ∧ 3 ≤ a1 ∧ 3 ≤ a2)) := by
  show (([a0,a1,a2].all fun x => decide (x < 3)) ||
        ([a0,a1,a2].all fun x => decide (3 ≤ x))) = true ↔ _
  simp only [List.all_cons, List.all_nil, Bool.and_true, Bool.and_eq_true,
    Bool.or_eq_true, decide_eq_true_eq]

/- --- §4a the finite subgroup facts (decide +kernel) --- -/

theorem G48_length : G48.length = 48 := by decide +kernel

theorem G24_length : G24.length = 24 := by decide +kernel

/-- TG-3 headline count: exactly 12 of the 48 constraint symmetries respect
    the trigram bipartition. -/
theorem G12_length : G12.length = 12 := by decide +kernel

/-- record level: the 12 collapse to exactly 6 coset representatives — the
    record-level trigram-compatible symmetry group is S₃ (order 6). -/
theorem G6_length : G6.length = 6 := by decide +kernel

theorem G12_sub_G48 : ∀ p ∈ G12, p ∈ G48 := fun _ hp => (List.mem_filter.mp hp).1

theorem idp_mem_G12 : idp ∈ G12 := by decide +kernel

/-- rho (bit reversal) is trigram-compatible — it SWAPS the two blocks. -/
theorem rho_mem_G12 : rho ∈ G12 := by decide +kernel

/-- G12 is closed under composition (with idp and inverses below, a genuine
    subgroup of G48). -/
theorem G12_closed_pcomp : ∀ p ∈ G12, ∀ q ∈ G12, pcomp p q ∈ G12 := by decide +kernel

theorem G12_closed_inv : ∀ p ∈ G12, ∃ q ∈ G12, pcomp q p = idp ∧ pcomp p q = idp := by
  decide +kernel

/-- rho is central in G48 (G48 IS the centralizer of reversal, so this is the
    expected bookkeeping fact, kernel-checked). -/
theorem rho_central_G48 : ∀ p ∈ G48, pcomp p rho = pcomp rho p := by decide +kernel

/- --- §4b structure: G12 ≅ S₃ × C₂, record level S₃ --- -/

/-- every 3-permutation embeds into the record-level representatives G6. -/
theorem mirrorDouble_mem_G6 : ∀ q ∈ perms3, mirrorDouble q ∈ G6 := by decide +kernel

/-- ... and its rho-coset partner lies in G12. -/
theorem mirrorDouble_rho_mem_G12 : ∀ q ∈ perms3, pcomp (mirrorDouble q) rho ∈ G12 := by
  decide +kernel

/-- COVERING: every element of G12 is mirrorDouble q or (mirrorDouble q)·rho
    for some 3-permutation q. With the 12 listed images distinct
    (G12_decomposition_nodup) and |G12| = 12, this is the exact decomposition
    G12 = S₃ × {id, rho} ≅ S₃ × C₂ (rho is central by rho_central_G48). -/
theorem G12_decomposition_covers :
    (G12.all fun p =>
      ((perms3.map mirrorDouble).contains p ||
       (perms3.map fun q => pcomp (mirrorDouble q) rho).contains p)) = true := by
  decide +kernel

theorem G12_decomposition_nodup :
    ((perms3.map mirrorDouble) ++ (perms3.map fun q => pcomp (mirrorDouble q) rho)).Nodup := by
  decide +kernel

/-- mirrorDouble is a group homomorphism S₃ → G48 (composition-compatible;
    with injectivity below, an isomorphism onto its image G6). -/
theorem mirrorDouble_hom :
    ∀ q1 ∈ perms3, ∀ q2 ∈ perms3,
      pcomp (mirrorDouble q1) (mirrorDouble q2) = mirrorDouble (pcomp q1 q2) := by
  decide +kernel

theorem mirrorDouble_inj :
    ∀ q1 ∈ perms3, ∀ q2 ∈ perms3, mirrorDouble q1 = mirrorDouble q2 → q1 = q2 := by
  decide +kernel

/-- the record-level representatives are EXACTLY the mirrorDouble image:
    G6 = mirrorDouble(S₃) (with mirrorDouble_mem_G6, both inclusions). -/
theorem G6_eq_mirrorDouble_image :
    (G6.all fun p => (perms3.map mirrorDouble).contains p) = true := by decide +kernel

/-- G6 sits inside Automorphism.lean's record-level G24 (so "6 of the 24
    record-level symmetries are trigram-compatible" is well-posed)... -/
theorem G6_sub_G24 : ∀ p ∈ G6, p ∈ G24 := by decide +kernel

/-- ... and conversely G6 exhausts the trigram-compatible part of G24. -/
theorem G24_blockPreserving_sub_G6 : ∀ p ∈ G24, blockPreserving p = true → p ∈ G6 := by
  decide +kernel

/- --- §4c the characterization: bipartition-preservation = blockwise action --- -/

set_option maxHeartbeats 2000000 in
/-- CHARACTERIZATION over all 720 line permutations: σ preserves the trigram
    bipartition iff the upper trigram of σ·h is a function of ONE trigram of
    h alone (the upper one if blocks are fixed, the lower one if swapped).
    This is the precise sense in which the other 36 elements of G48 "do not
    respect trigram structure": for them, no trigram of the image is
    determined by any single trigram of the input. -/
theorem blockPreserving_iff_blockwise :
    ∀ p ∈ perms idp,
      (blockPreserving p = true ↔
        ((∀ a, a < 64 → ∀ b, b < 64 → upperT a = upperT b →
            upperT (applyPerm p a) = upperT (applyPerm p b)) ∨
         (∀ a, a < 64 → ∀ b, b < 64 → lowerT a = lowerT b →
            upperT (applyPerm p a) = upperT (applyPerm p b)))) := by
  intro p hp
  have hperm : p.Perm idp := mem_perms_perm hp
  have hlen : p.length = 6 := hperm.length_eq
  have hnd : p.Nodup := hperm.nodup_iff.mpr (by decide)
  have hmem : ∀ j ∈ p, j < 6 := by
    intro j hj
    have : j ∈ idp := hperm.mem_iff.mp hj
    simp only [idp, List.mem_cons, List.not_mem_nil, or_false] at this
    omega
  -- destructure p into its six entries
  match p, hlen, hnd, hmem with
  | [a0, a1, a2, a3, a4, a5], _, hnd, hmem =>
  -- bounds
  have b0 : a0 < 6 := hmem a0 (by simp)
  have b1 : a1 < 6 := hmem a1 (by simp)
  have b2 : a2 < 6 := hmem a2 (by simp)
  have b3 : a3 < 6 := hmem a3 (by simp)
  have b4 : a4 < 6 := hmem a4 (by simp)
  have b5 : a5 < 6 := hmem a5 (by simp)
  -- pairwise distinctness, peeled into omega-friendly conjunctions of ≠
  obtain ⟨hm0, hnd⟩ := List.nodup_cons.mp hnd
  obtain ⟨hm1, hnd⟩ := List.nodup_cons.mp hnd
  obtain ⟨hm2, hnd⟩ := List.nodup_cons.mp hnd
  obtain ⟨hm3, hnd⟩ := List.nodup_cons.mp hnd
  obtain ⟨hm4, _⟩ := List.nodup_cons.mp hnd
  simp only [List.mem_cons, List.not_mem_nil, or_false, not_or] at hm0 hm1 hm2 hm3 hm4
  constructor
  · -- forward: block preservation ⇒ blockwise action
    intro hbp
    have hbp' : (a0 < 3 ∧ a1 < 3 ∧ a2 < 3) ∨ (3 ≤ a0 ∧ 3 ≤ a1 ∧ 3 ≤ a2) :=
      (blockPreserving6 a0 a1 a2 a3 a4 a5).mp hbp
    rcases hbp' with ⟨h0, h1, h2⟩ | ⟨h0, h1, h2⟩
    · -- blocks fixed: {a0,a1,a2} = {0,1,2}, so {a3,a4,a5} = {3,4,5};
      -- the upper trigram of σ·x is a function of x's upper trigram
      left
      intro a _ b _ hab
      rw [applyPerm6_split, applyPerm6_split]
      have hLa : a % 2 * 2^a0 + a/2 % 2 * 2^a1 + a/4 % 2 * 2^a2 ≤ 7 :=
        lowsum_le7 h0 h1 h2 (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
      have hLb : b % 2 * 2^a0 + b/2 % 2 * 2^a1 + b/4 % 2 * 2^a2 ≤ 7 :=
        lowsum_le7 h0 h1 h2 (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
      obtain ⟨La, hga⟩ : ∃ L, a % 2 * 2^a0 + a/2 % 2 * 2^a1 + a/4 % 2 * 2^a2 = L := ⟨_, rfl⟩
      obtain ⟨Lb, hgb⟩ : ∃ L, b % 2 * 2^a0 + b/2 % 2 * 2^a1 + b/4 % 2 * 2^a2 = L := ⟨_, rfl⟩
      rw [hga] at hLa ⊢
      rw [hgb] at hLb ⊢
      clear hga hgb
      simp only [upperT] at hab ⊢
      have hb3 : a/8 % 2 = b/8 % 2 := by omega
      have hb4 : a/16 % 2 = b/16 % 2 := by omega
      have hb5 : a/32 % 2 = b/32 % 2 := by omega
      rw [hb3, hb4, hb5]
      have e3 : a3 = 3 ∨ a3 = 4 ∨ a3 = 5 := by omega
      have e4 : a4 = 3 ∨ a4 = 4 ∨ a4 = 5 := by omega
      have e5 : a5 = 3 ∨ a5 = 4 ∨ a5 = 5 := by omega
      rcases e3 with rfl | rfl | rfl <;> rcases e4 with rfl | rfl | rfl <;>
        rcases e5 with rfl | rfl | rfl <;>
        simp only [show (2:Nat)^3 = 8 from rfl, show (2:Nat)^4 = 16 from rfl,
          show (2:Nat)^5 = 32 from rfl] <;> omega
    · -- blocks swapped: {a0,a1,a2} = {3,4,5}, so {a3,a4,a5} = {0,1,2};
      -- the upper trigram of σ·x is a function of x's lower trigram
      right
      intro a _ b _ hab
      rw [applyPerm6_split, applyPerm6_split]
      have g3 : a3 < 3 := by omega
      have g4 : a4 < 3 := by omega
      have g5 : a5 < 3 := by omega
      have hHa : a/8 % 2 * 2^a3 + a/16 % 2 * 2^a4 + a/32 % 2 * 2^a5 ≤ 7 :=
        lowsum_le7 g3 g4 g5 (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
      have hHb : b/8 % 2 * 2^a3 + b/16 % 2 * 2^a4 + b/32 % 2 * 2^a5 ≤ 7 :=
        lowsum_le7 g3 g4 g5 (by omega) (by omega) (by omega) (by omega) (by omega) (by omega)
      obtain ⟨Ha, hga⟩ : ∃ L, a/8 % 2 * 2^a3 + a/16 % 2 * 2^a4 + a/32 % 2 * 2^a5 = L := ⟨_, rfl⟩
      obtain ⟨Hb, hgb⟩ : ∃ L, b/8 % 2 * 2^a3 + b/16 % 2 * 2^a4 + b/32 % 2 * 2^a5 = L := ⟨_, rfl⟩
      rw [hga] at hHa ⊢
      rw [hgb] at hHb ⊢
      clear hga hgb
      simp only [upperT, lowerT] at hab ⊢
      have hb0 : a % 2 = b % 2 := by omega
      have hb1 : a/2 % 2 = b/2 % 2 := by omega
      have hb2 : a/4 % 2 = b/4 % 2 := by omega
      rw [hb0, hb1, hb2]
      have e0 : a0 = 3 ∨ a0 = 4 ∨ a0 = 5 := by omega
      have e1 : a1 = 3 ∨ a1 = 4 ∨ a1 = 5 := by omega
      have e2 : a2 = 3 ∨ a2 = 4 ∨ a2 = 5 := by omega
      rcases e0 with rfl | rfl | rfl <;> rcases e1 with rfl | rfl | rfl <;>
        rcases e2 with rfl | rfl | rfl <;>
        simp only [show (2:Nat)^3 = 8 from rfl, show (2:Nat)^4 = 16 from rfl,
          show (2:Nat)^5 = 32 from rfl] <;> omega
  · -- reverse: blockwise action ⇒ block preservation (contrapositive with
    -- explicit single-bit counterexamples)
    intro hc
    rcases Bool.eq_false_or_eq_true (blockPreserving [a0, a1, a2, a3, a4, a5]) with hT | hF
    · exact hT
    exfalso
    have hno : ¬((a0 < 3 ∧ a1 < 3 ∧ a2 < 3) ∨ (3 ≤ a0 ∧ 3 ≤ a1 ∧ 3 ≤ a2)) := by
      intro hyes
      have ht := (blockPreserving6 a0 a1 a2 a3 a4 a5).mpr hyes
      rw [ht] at hF
      exact Bool.noConfusion hF
    -- the closed image of zero
    have hz : applyPerm [a0, a1, a2, a3, a4, a5] 0 = 0 := by
      rw [applyPerm6_split]; simp
    -- a low source bit crossing up, and a low target position left uncovered
    have hi : 3 ≤ a0 ∨ 3 ≤ a1 ∨ 3 ≤ a2 := by omega
    rcases hc with hC1 | hC2
    · -- kill COND1 with a = 0, b = the crossing low bit
      rcases hi with hcr | hcr | hcr
      · have hinst := hC1 0 (by omega) 1 (by omega) (by simp [upperT])
        rw [hz, applyPerm6_split] at hinst
        simp only [upperT] at hinst
        have e : a0 = 3 ∨ a0 = 4 ∨ a0 = 5 := by omega
        rcases e with rfl | rfl | rfl <;> simp at hinst
      · have hinst := hC1 0 (by omega) 2 (by omega) (by simp [upperT])
        rw [hz, applyPerm6_split] at hinst
        simp only [upperT] at hinst
        have e : a1 = 3 ∨ a1 = 4 ∨ a1 = 5 := by omega
        rcases e with rfl | rfl | rfl <;> simp at hinst
      · have hinst := hC1 0 (by omega) 4 (by omega) (by simp [upperT])
        rw [hz, applyPerm6_split] at hinst
        simp only [upperT] at hinst
        have e : a2 = 3 ∨ a2 = 4 ∨ a2 = 5 := by omega
        rcases e with rfl | rfl | rfl <;> simp at hinst
    · -- kill COND2 with a = 0, b = an upper source bit that stays upper
      -- (exists: if all of a3,a4,a5 were < 3 they would exhaust {0,1,2},
      --  leaving no room for the low entry among a0,a1,a2)
      have hk : 3 ≤ a3 ∨ 3 ≤ a4 ∨ 3 ≤ a5 := by omega
      rcases hk with hcr | hcr | hcr
      · have hinst := hC2 0 (by omega) 8 (by omega) (by simp [lowerT])
        rw [hz, applyPerm6_split] at hinst
        simp only [upperT] at hinst
        have e : a3 = 3 ∨ a3 = 4 ∨ a3 = 5 := by omega
        rcases e with rfl | rfl | rfl <;> simp at hinst
      · have hinst := hC2 0 (by omega) 16 (by omega) (by simp [lowerT])
        rw [hz, applyPerm6_split] at hinst
        simp only [upperT] at hinst
        have e : a4 = 3 ∨ a4 = 4 ∨ a4 = 5 := by omega
        rcases e with rfl | rfl | rfl <;> simp at hinst
      · have hinst := hC2 0 (by omega) 32 (by omega) (by simp [lowerT])
        rw [hz, applyPerm6_split] at hinst
        simp only [upperT] at hinst
        have e : a5 = 3 ∨ a5 = 4 ∨ a5 = 5 := by omega
        rcases e with rfl | rfl | rfl <;> simp at hinst

/- --- §4d S₃-invariance of the trigram change-count functionals --- -/

/-- finite engine: every record-level trigram-compatible symmetry preserves
    equality of upper trigrams in both directions (block-fixing + injective
    on trigrams)... -/
theorem G6_upperT_iff :
    ∀ p ∈ G6, ∀ a, a < 64 → ∀ b, b < 64 →
      ((upperT (applyPerm p a) == upperT (applyPerm p b)) = (upperT a == upperT b)) := by
  decide +kernel

theorem G6_lowerT_iff :
    ∀ p ∈ G6, ∀ a, a < 64 → ∀ b, b < 64 →
      ((lowerT (applyPerm p a) == lowerT (applyPerm p b)) = (lowerT a == lowerT b)) := by
  decide +kernel

/-- S₃-INVARIANCE (structural, every sequence): the upper-trigram change
    count is invariant under every record-level trigram-compatible symmetry.
    This is the certification promised for the R7 corpus-scoreboard rider:
    the two trigram-locality functionals are S₃-relabel-invariant.
    (The rho-coset elements of G12 swap the two blocks and hence exchange
    uChange ↔ lChange; that swap variant is deliberately not formalized here
    — record-level representatives suffice for the battery gate.) -/
theorem uChange_mapP (p : List Nat) (hp : p ∈ G6) {l : List Nat}
    (hb : ∀ x ∈ l, x < 64) : uChange (l.map (applyPerm p)) = uChange l := by
  unfold uChange
  rw [← List.map_tail, List.zip_map]
  -- zip_map already yields a single map (Prod.map f f); no map_map fusion needed
  rw [List.countP_map]
  apply List.countP_congr
  intro ab hab
  have hmem := List.of_mem_zip hab
  have ha : ab.1 < 64 := hb _ hmem.1
  have hb2 : ab.2 < 64 := hb _ (List.mem_of_mem_tail hmem.2)
  simp only [Function.comp, Prod.map]
  -- goal: (upperT (applyPerm p ab.1) != upperT (applyPerm p ab.2))
  --     = (upperT ab.1 != upperT ab.2)
  have hiff := G6_upperT_iff p hp ab.1 ha ab.2 hb2
  simp [bne, hiff]
  -- confirmed 4.31.0: simp [bne, hiff] closes the != congruence as written

theorem lChange_mapP (p : List Nat) (hp : p ∈ G6) {l : List Nat}
    (hb : ∀ x ∈ l, x < 64) : lChange (l.map (applyPerm p)) = lChange l := by
  unfold lChange
  rw [← List.map_tail, List.zip_map]
  rw [List.countP_map]
  apply List.countP_congr
  intro ab hab
  have hmem := List.of_mem_zip hab
  have ha : ab.1 < 64 := hb _ hmem.1
  have hb2 : ab.2 < 64 := hb _ (List.mem_of_mem_tail hmem.2)
  simp only [Function.comp, Prod.map]
  have hiff := G6_lowerT_iff p hp ab.1 ha ab.2 hb2
  simp [bne, hiff]

/- --- §4e the NON-invariance corollary (methodological gate) --- -/

/-- the concrete witness: swapping bit positions 2 and 3 (a G24 element that
    is NOT trigram-compatible). -/
def sigmaW : List Nat := [0, 1, 3, 2, 4, 5]

theorem sigmaW_mem_G24 : sigmaW ∈ G24 := by decide +kernel

theorem sigmaW_not_blockPreserving : blockPreserving sigmaW = false := by decide

theorem uChange_KW : uChange KW = 59 := by decide +kernel

theorem lChange_KW : lChange KW = 58 := by decide +kernel

theorem uChange_KW_sigmaW : uChange (KW.map (applyPerm sigmaW)) = 62 := by decide +kernel

theorem sigmaW_image_valid : validC15 (KW.map (applyPerm sigmaW)) = true := by
  decide +kernel

/-- THE METHODOLOGICAL COROLLARY: trigram-defined functionals are NOT
    invariant on the 24-element record orbits of TR-5 — there is a
    record-level symmetry σ ∈ G24 carrying the valid ordering KW to a valid
    ordering in the same orbit with a DIFFERENT upper-trigram change count
    (62 vs 59). Consequence for any future measured trigram battery: only
    the order-6 refinement (G6, §4d) preserves trigram functionals, so
    per-orbit class counts under the DIV-24 gate do NOT extend to trigram
    functionals, and every battery functional must declare whether it is
    S₃-relabel-invariant. -/
theorem trigram_functional_not_orbit_invariant :
    ∃ p, p ∈ G24 ∧ validC15 (KW.map (applyPerm p)) = true ∧
      uChange (KW.map (applyPerm p)) ≠ uChange KW := by
  refine ⟨sigmaW, sigmaW_mem_G24, sigmaW_image_valid, ?_⟩
  rw [uChange_KW, uChange_KW_sigmaW]
  omega

/- ────────── §5a TG-4: nuclear naturality ──────────
   PRESUMABLY CLASSICAL/IMPLICIT (see header ledger): the 64→16→4 chain is
   commentary-tradition classical (Hershock 1991's "linking"; Cook 2006, the
   nuclear_adj battery source); the commutation and C1-descent facts are
   stated here without any discovery claim — they certify well-definedness
   under the shipped vdb_nuc (V-8) and nuclear_adj batteries. -/

theorem nuc_lt64 : ∀ h, h < 64 → nuc h < 64 := by decide

/-- TG-4.1: the nuclear map commutes with inversion. -/
theorem nuc_comm_rev : ∀ h, h < 64 → nuc (rev6 h) = rev6 (nuc h) := by decide

/-- TG-4.1: the nuclear map commutes with complement. -/
theorem nuc_comm_comp : ∀ h, h < 64 → nuc (h ^^^ 63) = nuc h ^^^ 63 := by decide

/-- TG-4.2: nuc maps symmetric hexagrams to symmetric hexagrams. -/
theorem nuc_preserves_symmetric : ∀ h, h < 64 → rev6 h = h → rev6 (nuc h) = nuc h := by
  decide

/-- TG-4.3 (C1-DESCENT): the canonical pairing descends along nuc — the
    nuclear image of a canonical pair {h, partner h} is always a pair of the
    form {x, rev6 x} (h non-symmetric) or {x, comp6 x} (h symmetric). -/
theorem nuc_partner_descent :
    ∀ h, h < 64 →
      nuc (partner h) = if rev6 h = h then nuc h ^^^ 63 else rev6 (nuc h) := by
  decide

/-- TG-4.4: image-size chain 64 → 16. -/
theorem nuc_image_16 : ((List.range 64).map nuc).eraseDups.length = 16 := by
  decide +kernel

/-- TG-4.4: image-size chain 64 → 16 → 4, with the classical terminal set
    {000000, 111111, 010101, 101010} = {0, 63, 21, 42} (the F5/VdB terminal
    set hardcoded in solve.c's f5_vdb_term; first-occurrence order shown). -/
theorem nuc_nuc_image_terminal :
    ((List.range 64).map fun h => nuc (nuc h)).eraseDups = [0, 21, 42, 63] := by
  decide +kernel

/-- the terminal set is nuc-closed: 0 and 63 are fixed; 21 ↔ 42 swap. -/
theorem nuc_terminal_closed : nuc 0 = 0 ∧ nuc 63 = 63 ∧ nuc 21 = 42 ∧ nuc 42 = 21 := by
  decide

/- ────────── §5b TG-5: vacuity guards ──────────
   GUARDS, NOT RESULTS (see header ledger): kernel-checked because each
   defuses a numerology claim. -/

/-- pure-ness is a pair-class invariant (Bool form of pure_closed_partner,
    for the counting engine). -/
theorem pure_partner_bool : ∀ h, h < 64 → pureHex (partner h) = pureHex h := by
  decide

theorem pure_count_range : ((List.range 64).countP pureHex) = 8 := by decide +kernel

theorem trigram_balance_range :
    ∀ t, t < 8 → ((List.range 64).countP fun h => upperT h == t) = 8 ∧
                 ((List.range 64).countP fun h => lowerT h == t) = 8 := by
  decide +kernel

/-- TG-5.1 (VACUITY GUARD — trigram balance is ordering-invariant): in ANY
    permutation of the 64 hexagrams — King Wen or otherwise — each of the 8
    trigrams appears exactly 8 times as upper trigram and 8 times as lower.
    This is a property of the SET (all (U,L) combinations occur once), so
    "the King Wen sequence balances the eight trigrams" carries zero
    information about the ordering. -/
theorem trigram_balance_invariant (l : List Nat) (hperm : l.Perm (List.range 64)) :
    ∀ t, t < 8 → (l.countP fun h => upperT h == t) = 8 ∧
                 (l.countP fun h => lowerT h == t) = 8 := by
  intro t ht
  have h := trigram_balance_range t ht
  exact ⟨(hperm.countP_eq _).trans h.1, (hperm.countP_eq _).trans h.2⟩
  -- confirmed 4.31.0: Perm.countP_eq explicit-arg shape as written (as in §2)

/-- TG-5.2 / TG-1.5 (VACUITY GUARD — pure adjacency is C1-forced): in EVERY
    C1-valid ordering, a pair-slot holds a pure hexagram in its even position
    iff it holds one in its odd position — pure hexagrams necessarily sit in
    pure-pure couples; their pairwise adjacency in King Wen (#1-2, #29-30,
    #51-52, #57-58) is forced by the pairing rule, not a design choice. Only
    the four slot POSITIONS are a degree of freedom. -/
theorem pure_pairslot_couple (l : List Nat) (hb : ∀ x ∈ l, x < 64)
    (hlen : l.length = 64) (h1 : c1ok l = true) :
    ∀ i, i < 32 → pureHex (l.getD (2*i+1) 0) = pureHex (l.getD (2*i) 0) := by
  intro i hi
  have hget := getD_lt64 hb hlen
  have hc1 := c1_getD hlen h1
  rw [hc1 i hi]
  exact pure_partner_bool _ (hget (2*i) (by omega))

/-- ... and the number of pure pair-slots is exactly 4 in every C1-valid
    ordering (8 pure hexagrams, two per slot). -/
theorem pure_pairslot_count (l : List Nat) (hperm : l.Perm (List.range 64))
    (h1 : c1ok l = true) :
    ((List.range 32).countP fun i => pureHex (l.getD (2*i) 0)) = 4 := by
  have hcore : 2 * ((List.range 32).countP fun i => pureHex (l.getD (2*i) 0)) =
      (List.range 64).countP pureHex :=
    within_double l hperm h1 pureHex pure_partner_bool
  have h8 := pure_count_range
  omega

/- ────────── §6 sanity instances at King Wen (decide +kernel) ──────────
   Guards against silently-vacuous general statements: each sequence-level
   theorem above is exercised on the concrete KW list. -/

/-- KW satisfies the hypotheses used above. -/
example : validC15 KW = true := by decide +kernel

/-- KW's boundary multiset instantiates the budget theorem. -/
example :
    ((List.range 31).countP fun k => ftr KW (2*k+1) == 1) = 2 ∧
    ((List.range 31).countP fun k => ftr KW (2*k+1) == 2) = 8 ∧
    ((List.range 31).countP fun k => ftr KW (2*k+1) == 3) = 13 ∧
    ((List.range 31).countP fun k => ftr KW (2*k+1) == 4) = 7 ∧
    ((List.range 31).countP fun k => ftr KW (2*k+1) == 6) = 1 := by
  decide +kernel

/-- KW's unique 9th-six boundary is k = 18 (pairs #37-38 → #39-40, hexagrams
    53,43 → 20,10), and the pangtong-successor identities hold there:
    20 = comp 43 and 10 = comp 53. -/
example : ftr KW 37 = 6 ∧ KW.getD 38 0 = KW.getD 37 0 ^^^ 63 ∧
    KW.getD 39 0 = KW.getD 36 0 ^^^ 63 := by decide +kernel

/-- KW's pure pair-slots are exactly {0, 14, 25, 28} (King Wen #1-2, #29-30,
    #51-52, #57-58). -/
example : (List.range 32).filter (fun i => pureHex (KW.getD (2*i) 0)) =
    [0, 14, 25, 28] := by decide +kernel

/-- a nontrivial G6 element (mirrorDouble of the swap (0 1)) preserves KW's
    trigram change counts, instantiating uChange_mapP/lChange_mapP. -/
example : uChange (KW.map (applyPerm (mirrorDouble [1, 0, 2]))) = 59 ∧
    lChange (KW.map (applyPerm (mirrorDouble [1, 0, 2]))) = 58 := by decide +kernel

/-- ... and mirrorDouble [1,0,2] = [1,0,2,3,5,4] really is the mirrored
    doubling (lower swap (0 1) pairs with upper swap (4 5), NOT (3 4)). -/
example : mirrorDouble [1, 0, 2] = [1, 0, 2, 3, 5, 4] := by decide

end Trigram

/-! ### Axiom audit (added 2026-08-01; expectation updated 2026-08-07)
Emits the trust base for every theorem in this file that is CITED BY NAME in the
public documentation, so the suite's `#print axioms` claims are OBSERVED rather than
statically inferred. Expected: `[propext, Classical.choice, Quot.sound]`, or
`[propext]` alone for the finite facts — Lean's standard axioms only. Any
`Lean.ofReduceBool` here means a `native_decide` (compiler trust) has crept back
in and the docs must say so; since 2026-08-07 this file carries none. -/
#print axioms Trigram.rev6_trigram_factor
#print axioms Trigram.comp6_trigram_componentwise
#print axioms Trigram.ham_trigram_split
#print axioms Trigram.symmetric_iff_trigram
#print axioms Trigram.symmetric_count_8
#print axioms Trigram.antisymmetric_count_8
#print axioms Trigram.pure_hexagrams_explicit
#print axioms Trigram.pure_pairs_explicit
#print axioms Trigram.within_double
#print axioms Trigram.pairdist_count_0
#print axioms Trigram.selfcomp_pair_count
#print axioms Trigram.within_multiset_general
#print axioms Trigram.boundary_budget_general
#print axioms Trigram.ninth_six_trigram
#print axioms Trigram.single_line_carry
#print axioms Trigram.c2_trigram_reading
#print axioms Trigram.pangtong_successor
#print axioms Trigram.flanking_exclusion
#print axioms Trigram.G12_length
#print axioms Trigram.G6_length
#print axioms Trigram.rho_central_G48
#print axioms Trigram.G12_decomposition_covers
#print axioms Trigram.mirrorDouble_hom
#print axioms Trigram.G6_eq_mirrorDouble_image
#print axioms Trigram.blockPreserving_iff_blockwise
#print axioms Trigram.uChange_mapP
#print axioms Trigram.lChange_mapP
#print axioms Trigram.trigram_functional_not_orbit_invariant
#print axioms Trigram.nuc_comm_rev
#print axioms Trigram.nuc_comm_comp
#print axioms Trigram.nuc_partner_descent
#print axioms Trigram.nuc_image_16
#print axioms Trigram.nuc_nuc_image_terminal
#print axioms Trigram.nuc_terminal_closed
#print axioms Trigram.pure_partner_bool
#print axioms Trigram.pure_count_range
#print axioms Trigram.trigram_balance_range
#print axioms Trigram.trigram_balance_invariant
#print axioms Trigram.pure_pairslot_couple
#print axioms Trigram.pure_pairslot_count
